import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,startActivity,finishActivity,cancelActivity,endDay,activityView,validateState,energyMax,updateAppearance,chooseEvent,buyItem,equipItem,prepareLoadedState} from '../src/core.js';
function doAction(s,id,opts={}){let v=activityView(s,id,opts);if(!v.available&&(s.used===7||s.energy<Math.max(0,v.energy))){endDay(s);v=activityView(s,id,opts);}assert.ok(v.available,`${id}: ${v.reason}`);const r=startActivity(s,id,opts);assert.ok(r.ok);const result=finishActivity(s,r.run.id,80);assert.ok(result.ok);return result;}
function train(s,k,value){while(s.skills[k]<value)doAction(s,k);}
function debut(){const s=newGame();train(s,'vocal',15);train(s,'dance',15);doAction(s,'audition');assert.equal(s.stage,1);return s;}
test('JSON round trip, start cancellation, stable minigame and duplicate completion',()=>{const s=newGame();assert.ok(validateState(JSON.parse(JSON.stringify(s))));const r=startActivity(s,'vocal').run;assert.equal(r.mini,'rhythm');assert.ok(cancelActivity(s,r.id).ok);assert.equal(s.energy,60);const r2=startActivity(s,'vocal').run;assert.equal(r.seed,r2.seed);finishActivity(s,r2.id);const before=JSON.stringify(s);assert.equal(finishActivity(s,r2.id).ok,false);assert.equal(JSON.stringify(s),before);assert.ok(validateState(s));});
test('free recovery, seven slots, no automatic date and companion synchronisation',()=>{const s=newGame();s.money=0;s.energy=0;s.stress=100;doAction(s,'rest');assert.equal(s.energy,25);assert.equal(s.day,1);for(let i=0;i<6;i++)doAction(s,'rest');assert.equal(startActivity(s,'rest').ok,false);endDay(s);assert.equal(s.day,2);assert.equal(s.energy,energyMax(s));assert.ok(s.members.every(m=>m.level===s.level));});
test('four careers grow through real actions to worldstar without paid lessons',()=>{for(const path of ['stage','acting','variety','song']){const s=debut();const journey={debut:s.day};const k=path==='stage'||path==='song'?'vocal':path;train(s,k,80);let guard=0;while(s.stage<4&&guard++<20000){journey[s.stage]??=s.day;if(s.stage===3&&!s.records.overseas){doAction(s,'overseas');continue;}if(path==='stage'){if(s.fans<1000){doAction(s,'eventshow');continue;}if(s.money<activityView(s,'concert').cost){doAction(s,'eventshow');continue;}if(s.stage>=3&&s.records.tour.length<3)doAction(s,'tour',{city:s.records.tour.length});else doAction(s,'concert');}else if(path==='acting'){doAction(s,s.projects.movie?'movie':'casting');}else if(path==='variety'){doAction(s,'interview');}else{if(s.money<100&&!s.projects.song)doAction(s,'stream');else doAction(s,'song');}}console.log(path,JSON.stringify({...journey,worldstar:s.day,actions:s.serial}));assert.equal(s.stage,4,`${path} did not reach worldstar`);assert.ok(validateState(s),`${path} final state invalid`);if(path!=='stage')assert.equal(s.skills.dance,15);}});
test('projects lock scale and annual awards preserve lifetime records',()=>{const s=debut();train(s,'acting',80);doAction(s,'casting');const scale=s.projects.movie.scale;doAction(s,'movie',{scale:4});assert.equal(s.projects.movie.scale,scale);doAction(s,'movie');doAction(s,'movie');assert.equal(s.records.movies,1);assert.ok(s.badges.includes('첫 연기 도전상'));s.day=84;s.annual={movies:3,audience:1000000,movieScores:[90,90,90],stage:{count:0,sum:0},variety:{count:0,sum:0},creation:{count:0,sum:0}};const r=endDay(s);assert.ok(r.summary.awards.includes('1년 연기 대상'));assert.equal(s.records.movies,1);assert.equal(s.annual.movies,0);});
test('malformed nested numeric values and active runs are rejected',()=>{const s=newGame();s.skills.vocal=NaN;assert.equal(validateState(s),false);const t=newGame();t.activeAction={id:'bad'};assert.equal(validateState(t),false);});
test('cancelling recovery refunds exactly and all seven activities offer minigames',()=>{const s=newGame();s.energy=55;const r=startActivity(s,'rest').run;assert.equal(s.energy,60);cancelActivity(s,r.id);assert.equal(s.energy,55);s.energy=60;let offers=0;for(let i=0;i<7;i++){const r=startActivity(s,'vocal');assert.ok(r.ok);if(r.run.mini)offers++;finishActivity(s,r.run.id);}assert.equal(offers,7);assert.equal(s.miniCount,0);});
test('active save restores one pending reward, event claims once, makeup allows no color',()=>{const s=newGame();updateAppearance(s,{makeup:{blush:'none',lip:'none'}});const r=startActivity(s,'vocal').run;const saved=JSON.parse(JSON.stringify(s));assert.ok(validateState(saved));assert.equal(saved.energy,52);finishActivity(saved,r.id);assert.equal(saved.used,1);assert.equal(saved.energy,52);endDay(saved);assert.ok(saved.event);assert.equal(chooseEvent(saved,0).ok,true);assert.equal(chooseEvent(saved,0).ok,false);const before=JSON.stringify(saved);assert.equal(startActivity(saved,'missing').ok,false);assert.equal(JSON.stringify(saved),before);});
test('low-score practice grows without failure; rest offers a recovery minigame',()=>{const s=newGame();const r=startActivity(s,'vocal').run;const result=finishActivity(s,r.id,0).result;assert.equal(result.practice,true);assert.equal(result.success,true);assert.ok(result.rewards.skills.vocal>0);s.miniCount=2;const rest=startActivity(s,'rest').run;assert.equal(rest.mini,'rest');const recovery=finishActivity(s,rest.id,0).result;assert.equal(recovery.relaxation,true);assert.equal(recovery.success,true);assert.equal(s.miniCount,0);});
test('movie pays fame and annual counters only at publication; scale survives promotion',()=>{const s=debut();train(s,'acting',30);doAction(s,'casting',{scale:1});const before={fame:s.fame,public:s.records.public,money:s.money};s.stage=2;for(let i=0;i<2;i++){doAction(s,'movie',{scale:2});assert.equal(s.projects.movie.scale,1);assert.equal(s.fame,before.fame);assert.equal(s.records.public,before.public);assert.equal(s.money,before.money);assert.equal(s.annual.movies,0);}doAction(s,'movie',{scale:2});assert.equal(s.records.public,before.public+1);assert.equal(s.annual.movies,1);assert.equal(s.works[0].scale,1);assert.ok(s.money-before.money<=700);assert.ok(s.records.audience<=20000);});
test('events rotate, obey cooldown, record choices once, and never queue over an unread event',()=>{
 const s=newGame(),seen=new Map();
 for(let i=0;i<50;i++){
  endDay(s);if(!s.event)continue;
  const {id,title}=s.event;if(seen.has(id))assert.ok(s.day-seen.get(id)>=10);seen.set(id,s.day);
  const before=s.history.length;assert.ok(chooseEvent(s,0).ok);assert.equal(s.history[0].title,title);assert.equal(s.history.length,before+1);assert.equal(chooseEvent(s,0).ok,false);
 }
 assert.ok(seen.size>=8);endDay(s);while(!s.event)endDay(s);const unread=JSON.stringify(s.event);endDay(s);assert.equal(JSON.stringify(s.event),unread);assert.ok(validateState(s));
});
test('agency unlocks top equipment and owned tiers never stack or charge twice',()=>{
 const s=newGame();s.money=5000;assert.equal(buyItem(s,'vocal-equipment-3').ok,false);assert.equal(s.money,5000);
 s.agency=true;assert.ok(buyItem(s,'vocal-equipment-3').ok);assert.ok(buyItem(s,'vocal-equipment-1').ok);assert.equal(s.equipment.vocal,3);
 const before=s.money;assert.equal(buyItem(s,'vocal-equipment-3').ok,false);assert.equal(s.money,before);
});
