export const KEY='splash-club-save-v1';
export const COLORS=['#38b7a3','#f17d79','#a28bd4','#e8bd46','#599bd5'];
export const ITEMS=[{id:'cap',name:'구름 수영모',type:'수영모',price:80,stat:'stability',bonus:.04,desc:'안정성 +4',icon:'◡'},{id:'suit',name:'웨이브 수영복',type:'수영복',price:140,stat:'base',bonus:.04,desc:'기본 속도 +0.04',icon:'♧'},{id:'fins',name:'오리발 물갈퀴',type:'물갈퀴',price:180,stat:'power',bonus:.12,desc:'추진력 +12',icon:'♬'},{id:'goggles',name:'클리어 수영안경',type:'수영안경',price:100,stat:'stability',bonus:.06,desc:'안정성 +6',icon:'∞'}];
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const needXP=l=>80+(l-1)*40;
export const START_STATS=[{base:.68,power:.65,stability:.5},{base:.66,power:.8,stability:.4},{base:.68,power:.55,stability:.6},{base:.72,power:.55,stability:.45},{base:.65,power:.75,stability:.58}];
export function newPlayer(name,color){return {version:1,name:name.trim().slice(0,12)||'모찌',color:clamp(color,0,4),level:1,xp:0,coins:120,stats:{...START_STATS[clamp(color,0,4)]},owned:[],equipped:[],records:{races:0,practices:0,best:null,maxCombo:0},place:'village',settings:{sound:true,offset:0},savedAt:null};}
export function validSave(p){const n=(v,a,b)=>Number.isFinite(v)&&v>=a&&v<=b;return !!p&&p.version===1&&typeof p.name==='string'&&p.name.length>0&&p.name.length<=12&&Number.isInteger(p.color)&&n(p.color,0,4)&&Number.isInteger(p.level)&&n(p.level,1,20)&&n(p.xp,0,needXP(p.level)-1)&&Number.isInteger(p.coins)&&n(p.coins,0,1e9)&&p.stats&&n(p.stats.base,.1,3)&&n(p.stats.power,0,3)&&n(p.stats.stability,0,1)&&Array.isArray(p.owned)&&Array.isArray(p.equipped)&&new Set(p.owned).size===p.owned.length&&new Set(p.equipped).size===p.equipped.length&&p.owned.every(id=>ITEMS.some(i=>i.id===id))&&p.equipped.every(id=>p.owned.includes(id))&&p.records&&['races','practices','maxCombo'].every(k=>Number.isInteger(p.records[k])&&n(p.records[k],0,1e9))&&(p.records.best===null||n(p.records.best,0,10000))&&['village','home','practice','stadium'].includes(p.place)&&p.settings&&typeof p.settings.sound==='boolean'&&n(p.settings.offset,-150,150)&&(p.savedAt===null||typeof p.savedAt==='string'&&Number.isFinite(Date.parse(p.savedAt)));}
export function readSave(storage){try{const raw=storage.getItem(KEY);if(!raw)return {player:null,error:null};const p=JSON.parse(raw);if(!validSave(p))throw Error('invalid');return {player:p,error:null};}catch{return {player:null,error:'저장 데이터를 읽을 수 없어요. 새로 시작할 수 있어요.'};}}
export function savePlayer(storage,p){const next={...p,savedAt:new Date().toISOString()};try{storage.setItem(KEY,JSON.stringify(next));p.savedAt=next.savedAt;return true;}catch{return false;}}
export function stats(p){const s={...p.stats};for(const id of p.equipped){const i=ITEMS.find(x=>x.id===id);s[i.stat]+=i.bonus;}return s;}
export function purchase(p,id){const i=ITEMS.find(x=>x.id===id);if(!i||p.owned.includes(id)||p.coins<i.price)return false;p.coins-=i.price;p.owned.push(id);p.equipped.push(id);return true;}
export function equip(p,id){if(!p.owned.includes(id))return;p.equipped=p.equipped.includes(id)?p.equipped.filter(x=>x!==id):[...p.equipped,id];}
export const comboBonus=c=>Math.min(c*.005,.2);
export const targetSpeed=(s,g,c)=>s.base*(1+s.power*g)*(1+comboBonus(c));
export function judge(error){const a=Math.abs(error);return a<=.060001?1:a<=.120001?.7:a<=.180001?.3:0;}
export function applyGroup(actor,scores,s){const avg=scores.reduce((a,b)=>a+b,0)/scores.length;const rate=avg>=actor.gauge?.25:clamp(.30-(s.stability-.4)*.6,.18,.30);actor.gauge=clamp(actor.gauge+rate*(avg-actor.gauge),0,1);actor.combo=scores.every(x=>x>=.7)?actor.combo+1:0;actor.maxCombo=Math.max(actor.maxCombo,actor.combo);}
export function reward(p,mode,rank,accuracy,maxCombo,time){const xp=mode==='practice'?25+Math.round(accuracy*.35):45+(5-rank)*12+Math.round(accuracy*.25);const coins=mode==='practice'?15+Math.round(accuracy*.15):25+(5-rank)*15;const old=p.level;p.xp+=xp;p.coins+=coins;while(p.level<20&&p.xp>=needXP(p.level)){p.xp-=needXP(p.level);p.level++;p.stats.base+=.012;p.stats.power+=.012;p.stats.stability+=.008;}if(p.level===20)p.xp=0;p.records[mode==='practice'?'practices':'races']++;p.records.maxCombo=Math.max(p.records.maxCombo,maxCombo);if(mode==='race')p.records.best=p.records.best===null?time:Math.min(time,p.records.best);return {xp,coins,levels:p.level-old};}
export function difficulty(level){return {label:level<3?'입문 리그':level<6?'도전 리그':'챔피언 리그',bpm:level<3?100:level<6?108:116,perfect:Math.min(.67,.27+level*.025),good:.23};}
export function chart(mode,level,duration=180){const bpm=mode==='practice'?100:difficulty(level).bpm;const step=60/bpm;const groups=[];for(let i=0,t=2.4;t<duration;i++,t+=step){let keys=[[0],[2],[1],[3]][i%4];if(mode==='race'&&level>=3&&i%16>=12)keys=i%2===0?[0,3]:[2,1];groups.push({time:t,keys,scores:keys.map(()=>null),done:false});if(mode==='race'&&level>=6&&i%8===7)groups.push({time:t+step/2,keys:[i%2?0:2],scores:[null],done:false});}return groups;}
export function random(seed){return ()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
