import {SKILLS,STAGES,ACTIVITIES,ITEMS,PERSONALITIES,EVERYDAY_EVENTS,APPEARANCE_OPTIONS,APPEARANCE_DEFAULTS,MINI_NAMES} from './data.js';
const keys=Object.keys(SKILLS),clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v)),copy=o=>JSON.parse(JSON.stringify(o)),map=v=>Object.fromEntries(keys.map(k=>[k,v]));
const annual=()=>({movies:0,audience:0,movieScores:[],stage:{count:0,sum:0},variety:{count:0,sum:0},creation:{count:0,sum:0}});
export const energyMax=s=>Math.min(100,60+(s.level-1)*2);
export const levelNeed=l=>100+(l-1)*20;
export const skillNeed=v=>20+v*2;
export const formatDay=d=>`${Math.floor((d-1)/84)+1}년 ${Math.floor(((d-1)%84)/7)+1}월 ${(d-1)%7+1}일`;
export function newGame(o={}) { const appearance={...APPEARANCE_DEFAULTS,skin:'#f5cfb4',hair:'#55435f',hairStyle:'long',eyes:'round',outfit:'starter-lavender',shoes:'basic',accessory:'none',makeup:{blush:'#f0a8bc',lip:'#d97691',sparkle:false}}; const s={version:1,id:`idol-${Math.random().toString(36).slice(2)}`,name:String(o.name||'하루').trim().slice(0,12)||'하루',groupName:String(o.groupName||'루미데이').trim().slice(0,12)||'루미데이',personality:PERSONALITIES.some(p=>p.id===o.personality)?o.personality:'steady',appearance,day:1,used:0,level:1,xp:0,skills:map(10),skillXp:map(0),mastery:map(0),energy:60,stress:0,money:300,fans:0,followers:0,fame:0,stage:0,members:[],inventory:['starter-lavender','starter-mint','starter-cream'],equipment:{vocal:0,dance:0,acting:0,variety:0},records:{public:0,concerts:0,movies:0,songs:0,variety:0,audience:0,streams:0,tour:[],overseas:false},projects:{},works:[],badges:[],history:[],event:null,settings:{music:.3,sfx:.6,easy:false,reducedMotion:false},activeAction:null,serial:0,miniCount:0,miniOffers:0,introVocal:false,retry:null,annual:annual(),claimed:[],seenEvents:{},curiousDay:0,pendingPersonality:null,agency:false}; updateAppearance(s,o.appearance||{});s.members=['나래','루아','소미','유리'].map((name,i)=>({name,specialty:keys[i],level:1,skills:map(10),appearance:{...copy(appearance),hair:['#65a99b','#82b7db','#bb966b','#9a7fb6'][i],hairStyle:['bob','twin','long','long'][i],outfit:s.appearance.outfit}}));syncGroupOutfits(s);return s; }
function skillGain(s,k,n){if(!k||!n)return;s.skillXp[k]+=n;while(s.skills[k]<100&&s.skillXp[k]>=skillNeed(s.skills[k])){s.skillXp[k]-=skillNeed(s.skills[k]);s.skills[k]++;}if(s.skills[k]===100){const oldStars=Math.floor(s.mastery[k]/1000);s.mastery[k]+=s.skillXp[k];s.skillXp[k]=0;if(Math.floor(s.mastery[k]/1000)>oldStars){const label=SKILLS[k]+' 전문가 별';if(!s.badges.includes(label))s.badges.push(label);const item='outfit-'+(20+keys.indexOf(k));if(!s.inventory.includes(item))s.inventory.push(item);}}}
function xpGain(s,n){const before=energyMax(s);s.xp+=n;while(s.xp>=levelNeed(s.level)){s.xp-=levelNeed(s.level);s.level++;}s.energy=Math.min(energyMax(s),s.energy+energyMax(s)-before);}
const best=s=>keys.reduce((a,b)=>s.skills[a]>=s.skills[b]?a:b);
function miniFor(id,skill){if(['makeup','exercise','beauty','meal','rest','play','gaming','snack','vacation'].includes(id))return id;if(id==='song')return'compose';if(id==='choreo')return'memory';if(id==='advert')return'acting';return {vocal:'rhythm',dance:'direction',acting:'acting',variety:'variety',charm:'beauty'}[skill]||'variety';}
export function activityView(s,id,o={}){const a=ACTIVITIES.find(a=>a.id===id);if(!a)return{available:false,reason:'알 수 없는 활동이에요.',cost:0,energy:0,scale:1,mini:null};let skill=a.skill;if((id==='lesson'&&keys.includes(o.skill)||id==='stream'&&['vocal','dance','variety'].includes(o.skill)))skill=o.skill;if(['broadcast','eventshow','concert','tour'].includes(id)&&['vocal','dance'].includes(o.skill))skill=o.skill;if(id==='agency'||id==='overseas')skill=best(s);const scale=s.projects[id]?.scale||clamp(Number.isInteger(o.scale)?o.scale:Math.max(1,s.stage),1,Math.max(1,s.stage)),mult=[1,1,5,50,100][scale];const cost=a.cost*(id==='concert'||id==='tour'?mult:1)*(a.project&&s.projects[id]?0:1);let reason=''; const need=(ok,msg)=>{if(!ok&&!reason)reason=msg;};
 need(!s.activeAction,'진행 중인 활동을 먼저 마쳐 주세요.');need(s.used<7,'오늘 7칸을 모두 썼어요. 오늘을 마쳐 주세요.');
 if(id==='choreo')need(s.skills.dance>=15,'춤 15가 필요해요.');if(id==='lesson')need(s.skills[skill]>=15,`${SKILLS[skill]} 15가 필요해요.`);
 if(id==='audition'){need(s.stage===0,'이미 데뷔했어요.');need(s.level>=3&&s.skills.vocal>=15&&s.skills.dance>=15,'레벨 3, 노래와 춤 15가 필요해요.');}
 if(a.public||a.project||['agency','casting'].includes(id))need(s.stage>=1,'데뷔 오디션을 먼저 통과해 주세요.');
 if(id==='agency')need(!s.agency&&s.fans>=1000,'팬 1,000명부터 도전해요. 소속사 합격은 한 번만 가능해요.');
 if(id==='broadcast')need(s.skills[skill]>=20,`${SKILLS[skill]} 20이 필요해요.`);if(['varietyshow','interview'].includes(id))need(s.skills.variety>=15,'예능감 15가 필요해요.');
 if(id==='advert')need(s.fans>=1000&&s.skills.charm>=20,'팬 1,000명과 매력 20이 필요해요.');
 if(['concert','tour'].includes(id))need(s.fans>=1000&&s.skills[skill]>=25,'팬 1,000명과 선택한 노래 또는 춤 25가 필요해요.');
 if(['casting','movie'].includes(id))need(s.skills.acting>=20,'연기 20이 필요해요.');if(id==='movie')need(!!s.projects.movie,'무료 캐스팅을 먼저 통과해 주세요.');if(id==='casting')need(!s.projects.movie,'진행 중인 영화를 먼저 완성해 주세요.');
 if(id==='album'||id==='song')need(s.skills.vocal>=(id==='song'?25:20),`노래 ${id==='song'?25:20}이 필요해요.`);
 if(['overseas','tour'].includes(id))need(s.stage>=3,'톱스타부터 열려요.');if(id==='overseas')need(!s.records.overseas,'해외 소개를 완료했어요.');if(id==='tour')need(Number.isInteger(o.city)&&o.city>=0&&o.city<3,'투어 도시를 골라 주세요.');
 need(s.money>=cost,`${cost-s.money}코인이 더 필요해요.`);need(s.energy>=Math.max(0,a.energy),`에너지 ${Math.max(0,a.energy)-s.energy}이 더 필요해요. 무료로 쉬어 보세요.`);
 const mini=miniFor(id,skill);
 return {...a,skill,scale,mult,cost,energy:id==='vacation'?-energyMax(s):a.energy,available:!reason,reason,mini,recommended:id==='audition'?20:id==='agency'?35:id==='casting'?25:(a.public||a.project)?[20,25,40,60,80][scale]:20};}
export function startActivity(s,id,o={}){const v=activityView(s,id,o);if(!v.available)return{ok:false,reason:v.reason};const retry=s.retry?.activityId===id?s.retry:null;const before={energy:s.energy,miniCount:s.miniCount,miniOffers:s.miniOffers,introVocal:s.introVocal};s.miniOffers++;s.miniCount=0;if(id==='vocal')s.introVocal=true;const run={id:`${s.id}-${++s.serial}`,activityId:id,skill:v.skill,scale:v.scale,mini:v.mini,seed:retry?.seed??((s.serial*48271+s.day*7919)%2147483647),preparation:o.preparation===60?60:80,cost:v.cost,energy:v.energy,slots:id==='vacation'?7-s.used:1,city:o.city??0,before};s.money-=run.cost;s.energy=clamp(s.energy-run.energy,0,energyMax(s));s.used+=run.slots;s.activeAction=run;s.retry=null;return{ok:true,run:copy(run)};}
export function cancelActivity(s,id){const r=s.activeAction;if(!r||r.id!==id)return{ok:false};s.money+=r.cost;s.energy=clamp(s.energy+r.energy,0,energyMax(s));s.used-=r.slots;Object.assign(s,r.before);s.retry={activityId:r.activityId,seed:r.seed,mini:r.mini};s.activeAction=null;return{ok:true};}
function scoreFor(s,a,r,d){let ability=s.skills[r.skill]||20;if(r.activityId==='audition')ability=s.skills.vocal*.4+s.skills.dance*.4+s.skills.charm*.2;else if(r.activityId==='agency')ability=s.skills[best(s)]*.8+s.skills.charm*.2;else if(a.public||['movie','casting'].includes(a.id))ability=ability*.8+s.skills[a.id==='advert'?'variety':'charm']*.2;const rec=r.activityId==='audition'?20:r.activityId==='agency'?35:r.activityId==='casting'?25:(a.public||a.project)?[20,25,40,60,80][r.scale]:20;return clamp(Math.round(Math.min(100,ability/rec*100)*.8+d*.2)-(s.stress>=80?5:s.stress>=60?3:0));}
const ranged=(range,score)=>range?range[0]+Math.round((range[1]-range[0])*score/100):0;
function career(s,high){const r=s.records,k=s.skills;return high?[(Math.max(k.vocal,k.dance)>=80&&r.concerts>=15&&r.tour.length>=3),(k.acting>=80&&r.movies>=10&&r.audience>=5000000),(k.variety>=80&&r.variety>=40&&s.followers>=1000000),(k.vocal>=80&&r.songs>=10&&r.streams>=3000000)]:[(Math.max(k.vocal,k.dance)>=45&&r.concerts>=3),(k.acting>=45&&r.movies>=3&&r.audience>=300000),(k.variety>=45&&r.variety>=10),(k.vocal>=45&&r.songs>=3&&r.streams>=100000)];}
function checkMilestones(s){const out=[];if(s.stage===1&&s.level>=8&&s.fans>=3000&&s.fame>=20&&s.records.public>=10){s.stage=2;out.push(STAGES[2]);}if(s.stage===2&&s.level>=15&&s.fans>=50000&&s.fame>=55&&career(s,false).some(Boolean)){s.stage=3;out.push(STAGES[3]);}if(s.stage===3&&s.level>=25&&s.fans>=1000000&&s.fame>=90&&career(s,true).some(Boolean)&&s.records.overseas){s.stage=4;out.push('월드스타! 새로운 이야기는 계속돼요.');}const milestones=[['첫 콘서트',s.records.concerts>0],['첫 영화',s.records.movies>0],['첫 자작곡',s.records.songs>0],...['fans','followers'].flatMap(k=>[1000,10000,100000,1000000].map(n=>[`${k==='fans'?'팬':'팔로워'} ${n}`,s[k]>=n]))];for(const [label,yes]of milestones)if(yes&&!s.claimed.includes(label)){s.claimed.push(label);const item=`outfit-${Math.min(24,s.claimed.length)}`;if(!s.inventory.includes(item))s.inventory.push(item);out.push(`${label} 기념 의상`);}return out;}
export function finishActivity(s,id,directScore=80,extras={}){const r=s.activeAction;if(!r||r.id!==id||!Number.isFinite(directScore))return{ok:false,reason:'이미 끝났거나 올바르지 않은 활동이에요.'};const a=ACTIVITIES.find(a=>a.id===r.activityId);let score=scoreFor(s,a,r,clamp(directScore)),success=score>=(a.id==='audition'||a.id==='casting'?65:a.id==='agency'?70:60);const rewards={money:0,fans:0,followers:0,xp:a.xp,skills:{}};let published=!!a.public,title=a.name,description='오늘도 한 걸음 성장했어요.',unlocks=[];const add=(k,n)=>{if(k)rewards.skills[k]=(rewards.skills[k]||0)+n;};add(r.skill,ranged(a.range,score)+(a.training?(s.equipment[r.skill]||0)+(s.personality==='steady'?1:0):0));if(['audition','broadcast','concert','tour'].includes(a.id)){rewards.skills={vocal:ranged(a.range,score),dance:ranged(a.range,score)};}if(s.personality==='curious'&&['movie','song','album','choreo','advert'].includes(a.id)&&s.curiousDay!==s.day){add(r.skill,2);s.curiousDay=s.day;}
 if(a.id==='audition'&&success){s.stage=1;rewards.fans=100;unlocks.push('데뷔! 공개 활동이 열렸어요.');if(!s.inventory.includes('outfit-24'))s.inventory.push('outfit-24');}
 if(a.id==='agency'&&success){s.agency=true;unlocks.push('오로라 엔터 작업실');}
 if(a.id==='casting'&&success)s.projects.movie={scale:r.scale,scores:[],melody:null};
 if(a.project){const p=s.projects[a.id]||{scale:r.scale,scores:[],melody:null};p.scores.push(score);if(a.id==='song'&&Array.isArray(extras.melody))p.melody=copy(extras.melody).slice(0,64);s.projects[a.id]=p;description=`${p.scores.length}/${a.project}회차 완료. 천천히 이어 가요.`;if(p.scores.length>=a.project){score=Math.round(p.scores.reduce((x,y)=>x+y,0)/p.scores.length);success=score>=60;published=true;const work={id:r.id,type:a.id,name:`${a.id==='movie'?'별빛 영화':a.id==='song'?'우리의 멜로디':'구름 음원'} ${s.serial}`,score,scale:p.scale,day:s.day,melody:p.melody};s.works.unshift(work);s.works=s.works.slice(0,100);delete s.projects[a.id];description=`${work.name} 발표!`;if(a.id==='movie'){s.records.movies++;s.annual.movies++;s.annual.movieScores.push(score);s.annual.movieScores=s.annual.movieScores.sort((a,b)=>b-a).slice(0,3);if(success&&!s.badges.includes('첫 연기 도전상')){s.badges.push('첫 연기 도전상');unlocks.push('첫 연기 도전상');}}if(a.id==='song'&&success)s.records.songs++;}}
 if(published){const mult=[1,1,5,50,100][r.scale]*(a.id==='song'?1.5:1);for(const k of ['money','fans','followers'])rewards[k]+=Math.round(ranged(a[k],score)*mult);const countMult=[1,1,5,20,50][r.scale]*(a.id==='song'?1.5:1);for(const k of ['audience','streams']){const n=Math.round(ranged(a[k],score)*countMult);s.records[k]+=n;if(k==='audience')s.annual.audience+=n;}s.records.public++;s.fame=clamp(s.fame+(score>=85?2:1));if(s.personality==='sparkle')rewards.xp+=2;if(success){let category=null;if(['concert','tour','broadcast','eventshow'].includes(a.id))category='stage';if(['varietyshow','interview'].includes(a.id)){s.records.variety++;category='variety';if(score>=85&&!s.seenEvents.viral&&!s.event)s.event={id:'viral',title:'인터뷰 한마디가 화제',text:'따뜻한 한마디가 많은 사람에게 닿았어요.',choices:[{text:'짧은 후속 영상',effect:'팔로워 +100 · 스트레스 +2',followers:100,stress:2},{text:'멤버들과 감사 인사',effect:'팬 +80 · 스트레스 −5',fans:80,stress:-5}]};}if(['song','album'].includes(a.id))category='creation';if(category){s.annual[category].count++;s.annual[category].sum+=score;}if(['concert','tour'].includes(a.id))s.records.concerts++;if(a.id==='tour'&&!s.records.tour.includes(r.city))s.records.tour.push(r.city);}if(a.id==='overseas')s.records.overseas=true;}
 if(a.id==='makeup'&&extras.makeup)updateAppearance(s,{makeup:extras.makeup});for(const [k,n]of Object.entries(rewards.skills))skillGain(s,k,n);xpGain(s,rewards.xp);for(const k of ['money','fans','followers'])s[k]+=rewards[k];const oldStress=s.stress;s.stress=clamp(s.stress+a.stress-(s.personality==='kind'&&a.energy<0?2:0));rewards.energy=s.energy-r.before.energy;rewards.stress=s.stress-oldStress;s.activeAction=null;unlocks.push(...checkMilestones(s));const practice=!!a.training||['exercise','beauty','makeup'].includes(a.id),relaxation=a.energy<0;if(practice||relaxation||a.id==='overseas')success=true;const result={id:r.id,title,score,success,practice,relaxation,description,rewards,unlocks,endDay:a.id==='vacation',fanReaction:published?(['오늘 모습이 오래 기억날 것 같아요!','우리도 함께 따라 불렀어요. 다음 무대가 기다려져요!','한 걸음씩 자라는 모습을 응원하고 있어요.','다섯 친구가 함께하니 더 즐거워요!'][s.serial%4]):null};s.history.unshift({day:s.day,...copy(result)});s.history=s.history.slice(0,100);return{ok:true,result};}
export function progression(s){const r=s.records,k=s.skills;return[{name:'데뷔',description:'레벨 3 · 노래/춤 15 · 오디션 합격',done:s.stage>=1},{name:'인기 아이돌',description:'레벨 8 · 팬 3천 · 인지도 20 · 공개 10회',done:s.stage>=2},{name:'톱스타',description:'레벨 15 · 팬 5만 · 인지도 55 · 경력 중간 목표',done:s.stage>=3},{name:'월드스타',description:'레벨 25 · 팬 100만 · 인지도 90 · 최고 목표와 해외 소개',done:s.stage>=4},...['무대','배우','예능','싱어송라이터'].map((name,i)=>({name:`${name} 경력`,description:[`노래/춤 45→80 · 콘서트 3→15 · 투어 ${r.tour.length}/3도시`,`연기 45→80 · 영화 3→10 · 관객 30만→500만`,`예능감 45→80 · 방송 10→40 · 팔로워 100만`,`노래 45→80 · 자작곡 3→10 · 재생 10만→300만`][i],done:career(s,true)[i],middle:career(s,false)[i]}))];}
export const nextGoal=s=>progression(s).find(g=>!g.done)?.description||'새 작품과 전문가 별 기록을 모아 보세요.';
export function endDay(s){if(s.activeAction)return{ok:false,reason:'진행 중인 활동을 먼저 끝내 주세요.'};const awards=[];if(s.day%84===0){const y=Math.ceil(s.day/84),a=s.annual;if(a.movies>=3&&a.movieScores.length===3&&a.movieScores.reduce((x,y)=>x+y,0)/3>=85&&a.audience>=1000000)awards.push(`${y}년 연기 대상`);for(const [k,n]of [['stage','무대'],['variety','예능'],['creation','창작']])if(a[k].count>=10&&a[k].sum/a[k].count>=85)awards.push(`${y}년 ${n} 대상`);s.badges.push(...awards);s.annual=annual();}const top=Math.max(...Object.values(s.skills));for(const m of s.members){m.level=s.level;for(const k of keys)m.skills[k]=k===m.specialty?Math.min(top,Math.max(10,Math.round(top*.9))+3):Math.max(10,Math.round(top*.9));}const summary={day:s.day,date:formatDay(s.day),activities:s.used,awards,members:s.members.map(m=>`${m.name}: 오늘도 함께 자랐어요!`)};s.day++;s.used=0;s.energy=energyMax(s);s.stress=clamp(s.stress-15);s.miniCount=0;s.miniOffers=0;s.retry=null;if(s.pendingPersonality){s.personality=s.pendingPersonality;s.pendingPersonality=null;}if(!s.event)queueEvent(s);return{ok:true,summary};}
function queueEvent(s){
 if(s.day===2){s.event={id:'guide',title:'쉬어도 괜찮아요',text:'무료 휴식과 오늘 마치기로 언제든 다시 힘을 낼 수 있어요.',choices:[{text:'좋아요',effect:'스트레스 −5',stress:-5}]};return;}
 if(s.day<3||s.day%2===0)return;
 if(s.stage>=1&&s.skills.acting>=20&&!s.seenEvents.casting){s.event={id:'casting',title:'작은 영화의 캐스팅 제안',text:'새로운 배역에 도전할 수 있어요. 언제든 촬영장에서 무료 캐스팅을 골라 주세요.',choices:[{text:'대본 받아 보기',effect:'무료 캐스팅 안내'},{text:'나중에 도전하기',effect:'제안은 계속 열려 있어요'}]};return;}
 const note={id:'note',title:'나래의 연습실 메모',text:'오늘 발견한 노래 이야기를 함께 나눌까요?',choices:[{text:'같이 읽어 보기',effect:'노래 경험치 +'+(s.personality==='steady'?10:8),skill:'vocal',amount:s.personality==='steady'?10:8},{text:'쉬며 이야기하기',effect:'스트레스 −'+(s.personality==='kind'?12:10),stress:s.personality==='kind'?-12:-10}]};
 const candidates=[note,...EVERYDAY_EVENTS].filter(e=>s.stage>=(e.stage||0)&&(!s.seenEvents[e.id]||s.day-s.seenEvents[e.id]>=10));
 candidates.sort((a,b)=>(s.seenEvents[a.id]||0)-(s.seenEvents[b.id]||0));
 if(candidates.length)s.event=copy(candidates[0]);
}
export function chooseEvent(s,index){if(!s.event||s.activeAction||!Number.isInteger(index)||!s.event.choices[index])return{ok:false};const c=s.event.choices[index],result={title:s.event.title,description:c.text+' · '+c.effect};if(c.skill)skillGain(s,c.skill,c.amount);s.stress=clamp(s.stress+(c.stress||0));s.fans+=c.fans||0;s.followers+=c.followers||0;s.seenEvents[s.event.id]=s.day;s.history.unshift({day:s.day,...result});s.history=s.history.slice(0,100);s.event=null;return{ok:true,result};}
export function buyItem(s,id){const i=ITEMS.find(i=>i.id===id);if(!i)return{ok:false,reason:'알 수 없는 물건이에요.'};if(s.inventory.includes(id))return{ok:false,reason:'이미 가지고 있어요.'};if(i.type==='equipment'&&i.tier===3&&!s.agency)return{ok:false,reason:'대형 소속사에 합격하면 열려요.'};if(s.money<i.price)return{ok:false,reason:'코인이 부족해요.'};s.money-=i.price;s.inventory.push(id);if(i.type==='equipment')s.equipment[i.skill]=Math.max(s.equipment[i.skill],i.tier);return{ok:true};}
export function equipItem(s,id){const i=ITEMS.find(i=>i.id===id);if(!i||!s.inventory.includes(id)||i.type==='equipment')return{ok:false,reason:'먼저 구입해 주세요.'};s.appearance[i.type]=id;syncGroupOutfits(s);return{ok:true};}
export function changePersonality(s,id){if(!PERSONALITIES.some(p=>p.id===id))return{ok:false};s.pendingPersonality=id;return{ok:true};}
export function updateAppearance(s,p){if(!p||typeof p!=='object')return{ok:false};const color=x=>typeof x==='string'&&/^#[\da-f]{6}$/i.test(x);for(const k of ['skin','hair','eyeColor'])if(color(p[k]))s.appearance[k]=p[k];for(const [key,options] of Object.entries(APPEARANCE_OPTIONS))if(Object.hasOwn(options.values,p[key]))s.appearance[key]=p[key];if(typeof p.freckles==='boolean')s.appearance.freckles=p.freckles;for(const k of ['outfit','shoes','accessory'])if(s.inventory.includes(p[k]))s.appearance[k]=p[k];if(p.makeup&&typeof p.makeup==='object'){for(const k of ['blush','lip'])if(color(p.makeup[k])||p.makeup[k]==='none')s.appearance.makeup[k]=p.makeup[k];if(typeof p.makeup.sparkle==='boolean')s.appearance.makeup.sparkle=p.makeup.sparkle;}syncGroupOutfits(s);return{ok:true};}
export function updateSettings(s,p){if(!p||typeof p!=='object')return{ok:false};for(const k of ['music','sfx'])if(Number.isFinite(p[k]))s.settings[k]=clamp(p[k],0,1);for(const k of ['easy','reducedMotion'])if(typeof p[k]==='boolean')s.settings[k]=p[k];return{ok:true};}
function validStructure(s){
 const obj=x=>x&&typeof x==='object'&&!Array.isArray(x),num=x=>typeof x==='number'&&Number.isFinite(x)&&x>=0,col=x=>typeof x==='string'&&/^#[\da-f]{6}$/i.test(x),app=x=>obj(x)&&col(x.skin)&&col(x.hair)&&Object.hasOwn(APPEARANCE_OPTIONS.hairStyle.values,x.hairStyle)&&Object.hasOwn(APPEARANCE_OPTIONS.eyes.values,x.eyes)&&Object.entries(APPEARANCE_OPTIONS).every(([k,o])=>x[k]===undefined||Object.hasOwn(o.values,x[k]))&&(x.eyeColor===undefined||col(x.eyeColor))&&(x.freckles===undefined||typeof x.freckles==='boolean')&&typeof x.outfit==='string'&&typeof x.shoes==='string'&&typeof x.accessory==='string'&&obj(x.makeup)&&(col(x.makeup.blush)||x.makeup.blush==='none')&&(col(x.makeup.lip)||x.makeup.lip==='none')&&typeof x.makeup.sparkle==='boolean';
 if(!obj(s)||!app(s.appearance)||!obj(s.settings)||!['music','sfx'].every(k=>num(s.settings[k])&&s.settings[k]<=1)||!['easy','reducedMotion'].every(k=>typeof s.settings[k]==='boolean'))return false;
 if(!obj(s.annual)||!num(s.annual.movies)||!num(s.annual.audience)||!Array.isArray(s.annual.movieScores)||s.annual.movieScores.length>3||s.annual.movieScores.some(n=>!num(n)||n>100))return false;
 for(const k of ['stage','variety','creation'])if(!obj(s.annual[k])||!num(s.annual[k].count)||!num(s.annual[k].sum))return false;
 for(const k of ['inventory','badges','claimed'])if(!Array.isArray(s[k])||s[k].some(x=>typeof x!=='string'))return false;
 if(!Array.isArray(s.members)||s.members.some(m=>!app(m.appearance)))return false;
 if(!Array.isArray(s.works)||s.works.some(w=>!obj(w)||typeof w.id!=='string'||typeof w.name!=='string'||!['movie','album','song'].includes(w.type)||!num(w.score)||w.score>100))return false;
 if(s.event!==null&&(!obj(s.event)||typeof s.event.id!=='string'||typeof s.event.title!=='string'||!Array.isArray(s.event.choices)||!s.event.choices.length||s.event.choices.some(c=>!obj(c)||typeof c.text!=='string'||typeof c.effect!=='string')))return false;
 if(s.pendingPersonality!==null&&!PERSONALITIES.some(p=>p.id===s.pendingPersonality))return false;
 const minis=[null,...Object.keys(MINI_NAMES)];
 if(s.retry!==null&&(!obj(s.retry)||!ACTIVITIES.some(a=>a.id===s.retry.activityId)||!num(s.retry.seed)||!minis.includes(s.retry.mini)))return false;
 if(s.activeAction){const r=s.activeAction;if(!minis.includes(r.mini)||!obj(r.before)||!num(r.before.energy)||!num(r.before.miniCount)||!num(r.before.miniOffers)||typeof r.before.introVocal!=='boolean'||!(r.skill===null||keys.includes(r.skill)))return false;}
 return typeof s.introVocal==='boolean'&&typeof s.agency==='boolean';
}
export function validateState(s){try{if(!validStructure(s))return false;const finite=(x,min=0,max=Number.MAX_SAFE_INTEGER)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max;const integer=(x,min=0,max=Number.MAX_SAFE_INTEGER)=>finite(x,min,max)&&Number.isInteger(x);if(!s||s.version!==1||typeof s.id!=='string'||!s.id||typeof s.name!=='string'||typeof s.groupName!=='string'||!PERSONALITIES.some(p=>p.id===s.personality))return false;for(const k of ['day','level'])if(!integer(s[k],1))return false;for(const k of ['money','fans','followers','xp','serial','curiousDay'])if(!finite(s[k]))return false;if(!integer(s.used,0,7)||!integer(s.stage,0,4)||!finite(s.energy,0,energyMax(s))||!finite(s.stress,0,100)||!finite(s.fame,0,100)||!integer(s.miniCount,0,2)||!integer(s.miniOffers,0,7))return false;for(const k of keys)if(!integer(s.skills[k],0,100)||!finite(s.skillXp[k])||!finite(s.mastery[k]))return false;for(const k of ['vocal','dance','acting','variety'])if(!integer(s.equipment[k],0,3))return false;for(const k of ['inventory','works','badges','history','claimed','members'])if(!Array.isArray(s[k]))return false;if(s.members.length!==4||s.history.length>100||s.works.length>100||s.inventory.some(id=>!ITEMS.some(i=>i.id===id)))return false;for(const m of s.members)if(typeof m.name!=='string'||!keys.includes(m.specialty)||!integer(m.level,1)||keys.some(k=>!finite(m.skills[k],0,100)))return false;for(const k of ['public','concerts','movies','songs','variety','audience','streams'])if(!finite(s.records[k]))return false;if(!Array.isArray(s.records.tour)||s.records.tour.some(n=>!integer(n,0,2))||typeof s.records.overseas!=='boolean')return false;if(!s.projects||!s.annual||!s.seenEvents||!s.settings||!s.appearance?.makeup)return false;for(const [id,p]of Object.entries(s.projects))if(!['movie','album','song'].includes(id)||!integer(p.scale,1,4)||!Array.isArray(p.scores)||p.scores.length>=ACTIVITIES.find(a=>a.id===id).project||p.scores.some(n=>!finite(n,0,100)))return false;if(s.activeAction){const r=s.activeAction;if(typeof r.id!=='string'||!ACTIVITIES.some(a=>a.id===r.activityId)||!integer(r.scale,1,4)||!integer(r.seed)||!finite(r.cost)||!finite(r.energy,-100,100)||!integer(r.slots,1,7)||!r.before||![60,80].includes(r.preparation))return false;}const walk=(v,depth=0)=>{if(depth>20)return false;if(typeof v==='number')return Number.isFinite(v);if(v===null||['string','boolean'].includes(typeof v))return true;if(typeof v==='object')return Object.values(v).every(x=>walk(x,depth+1));return false;};return walk(s);}catch{return false;}}

export function syncGroupOutfits(s){for(const m of s.members||[])for(const key of ['outfit','shoes','accessory'])m.appearance[key]=s.appearance[key];}
export function prepareLoadedState(s){s.appearance={...APPEARANCE_DEFAULTS,...s.appearance};for(const m of s.members)m.appearance={...APPEARANCE_DEFAULTS,...m.appearance};syncGroupOutfits(s);for(const r of [s.activeAction,s.retry])if(r&&!r.mini)r.mini=miniFor(r.activityId,r.skill||ACTIVITIES.find(a=>a.id===r.activityId)?.skill);return s;}
