import { BUBBLES_ICON, PAUSE_ICON } from './icons.js';
import {vocalChart,movePitch,vocalScore,VOCAL_PITCHES,memorySequences,danceChart,createDanceRun,DANCE_BEAT_MS,DANCE_DURATION_MS,RHYTHM_BEAT_MS,RHYTHM_DURATION_MS} from './rhythm.js';
import {MINI_NAMES} from './data.js';
import {mountExtraMinigame} from './extra-minigames.js';
const DIRS = ['↑', '→', '↓', '←'];
const arrowIcon = d => `<svg class="mini-arrow-icon" viewBox="0 0 40 40" aria-hidden="true" focusable="false"><g transform="rotate(${d*90} 20 20)" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 31V9M9 20 20 9 31 20"/></g></svg>`;
const KEYS = ['ArrowUp', 'ArrowRight', 'ArrowDown', 'ArrowLeft'];
const TITLES = MINI_NAMES;
const GUIDES = {
 rhythm:'→ 높이기 · ← 낮추기를 누르고 있으면 내 음정이 움직여요. 다음 음표의 음정에 맞추고, 음표가 가운데 별에 오면 Space 또는 박자 버튼을 눌러요. 음정과 박자를 함께 맞춰요!',direction:'위에서 내려오는 화살표가 아래 초록 판정 구간에 오면 같은 방향키를 눌러요. 총 10번 맞추면 완료! 조금 빠르거나 늦어도 괜찮아요. 아래 화살표 버튼으로도 할 수 있어요.',memory:'매번 무작위로 정해지는 4~6개 방향을 기억하고 따라 해요. 세 번의 안무에 도전해요. 다시 보기도 가능해요.',
 acting:'섞인 영화 장면을 필름 칸에 넣어 이야기를 완성해요. 장면 선택 후 칸을 누르거나 드래그해요.',variety:'제시어에 맞는 단어 세 개를 찾아요! 동물, 과일, 악기 주제가 바뀌어요. 숫자 1~9도 사용할 수 있어요.',makeup:'볼, 입술, 눈두덩, 아이라인, 눈썹 색과 반짝이를 자유롭게 꾸며요. 외모는 채점하지 않아요.',compose:'네 마디의 음과 악기를 골라 나만의 노래를 만들어요. 끝까지 들어 보고 완성해요.',
 exercise:'자동으로 달리는 동안 Space 또는 점프 버튼을 눌러 장애물을 뛰어넘어요. 장애물 10개를 지나면 완주! 부딪혀도 계속 달릴 수 있어요.',beauty:'얼굴의 거품을 손가락으로 문질러 닦아요. 하나씩 클릭하거나 Tab·Enter로 눌러도 돼요.',meal:'곡물·단백질·채소를 골라 도시락 세 칸을 채워요. 마음에 드는 조합이면 모두 좋아요.',rest:'구름을 키우고 줄이는 느긋한 놀이예요. 세 번 함께 쉬면 완료! 점수 경쟁은 없어요.',play:'뒤집은 카드의 그림을 기억해 같은 친구 두 장을 찾아요. 시간 제한이 없어요.',gaming:'바구니를 좌우로 움직여 떨어지는 별을 받아요. 구름은 피해 봐요! 터치·드래그·방향키로 조작해요.',snack:'좌우로 움직이는 과일을 아래 과일 위에 쌓아요. 버튼이나 Space로 다섯 번 내려놓아요.',vacation:'해변 지도에서 조개·별·게·산호를 찾아 여행 엽서를 만들어요. 시간 제한 없이 쉬어 가요.'
};
export const rhythmScore = (delta,easy=false) => Math.abs(delta) <= (easy?250:180) ? 100 : Math.abs(delta) <= (easy?450:320) ? 70 : 0;
export function startMinigame(container, options) {
  const o = {level:1,easy:false,seed:1,tone:()=>{},onComplete:()=>{},onCancel:()=>{},onFallback:()=>{},...options};
  const type = TITLES[o.type] ? o.type : 'rhythm';
  const tier = o.easy ? 0 : o.level >=16 ? 2 : o.level >=6 ? 1 : 0;
  let seed = (o.seed >>> 0)||1;
  const rand = () => {seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  let dead=false,paused=false,beginning=false,started=false,elapsed=0,last=0,raf=0,jobs=[],tick=()=>{},input=()=>{},keyUp=()=>{},onPause=()=>{},finished=false,rhythmMusic=null;
  const events=new AbortController();
  const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  const root=el('section','minigame'); root.setAttribute('aria-label',TITLES[type]); container.replaceChildren(root);
  const header=el('header','mini-header'); const heading=el('h2','',TITLES[type]);header.append(heading);root.append(header);
  const button=(label,fn,cls='')=>{const b=el('button',`mini-button ${cls}`,label);b.type='button';b.addEventListener('click',()=>{if(!dead&&b.isConnected&&(!paused||!body.contains(b)))fn();});return b;};
  const pauseButton=button('잠깐 쉬기',()=>pause());pauseButton.innerHTML=PAUSE_ICON+' 잠깐 쉬기';header.append(pauseButton);
  const body=el('div','mini-body');root.append(body);
  const overlay=el('div','mini-overlay');overlay.hidden=true;root.append(overlay);
  const footer=el('footer','mini-footer');footer.append(button('일반 활동으로 바꾸기',()=>exit(o.onFallback)),button('취소 · 일정과 비용 돌려받기',()=>exit(o.onCancel)));root.append(footer);
  const say=()=>{const p=el('p','mini-feedback','함께 해 볼까요?');p.setAttribute('aria-live','polite');body.append(p);return p;};
  const schedule=(delay,fn)=>{jobs.push({at:elapsed+delay,fn});};
  const sound=(f,d=.12)=>{if(!paused&&!dead)o.tone(f,d);};
  function destroy(){if(dead)return;dead=true;rhythmMusic?.stop();cancelAnimationFrame(raf);jobs=[];events.abort();}
  function exit(fn){destroy();fn();}
  function finish(score,extras={}){if(finished||dead)return;finished=true;exit(()=>o.onComplete(Math.round(Math.max(0,Math.min(100,score))),extras));}
  function pause(){if(dead||paused)return;paused=true;rhythmMusic?.pause();onPause();root.classList.add('mini-paused');overlay.replaceChildren(el('div','mini-pause-icon','☁'),el('h3','','잠깐 쉬어 가요'),el('p','','돌아오면 이어서 할 수 있어요.'),button('▶ 이어 하기',resume,'mini-primary'));overlay.hidden=false;body.inert=true;overlay.querySelector('button').focus();}
  function resume(){if(dead||!paused||document.hidden)return;paused=false;rhythmMusic?.resume();root.classList.remove('mini-paused');last=performance.now();overlay.hidden=true;body.inert=false;}
  document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();},{signal:events.signal});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();paused?resume():pause();return;}if(dead||paused||!started)return;if(e.target?.matches?.('input,textarea,select,[contenteditable=true]'))return;const gameKey=(KEYS.includes(e.key)&&['direction','memory','gaming'].includes(type))||(type==='rhythm'&&['ArrowLeft','ArrowRight'].includes(e.key))||(e.code==='Space'&&['rhythm','exercise','snack'].includes(type))||(/^[1-9]$/.test(e.key)&&['acting','variety','compose'].includes(type));if(gameKey){e.preventDefault();if(!e.repeat)input(e);}}, {signal:events.signal});
  document.addEventListener('keyup',e=>{if(!dead&&!paused&&started&&((type==='exercise'&&e.code==='Space')||(type==='rhythm'&&['ArrowLeft','ArrowRight'].includes(e.key)))){e.preventDefault();keyUp(e);}}, {signal:events.signal});
  function frame(now){if(dead)return;if(!last)last=now;if(!paused){elapsed+=Math.min(now-last,100);const ready=jobs.filter(j=>j.at<=elapsed);jobs=jobs.filter(j=>j.at>elapsed);ready.forEach(j=>{if(!dead)j.fn();});if(!dead)tick(elapsed);}last=now;if(!dead)raf=requestAnimationFrame(frame);}
  raf=requestAnimationFrame(frame);
  function pad(label,fn,cls=''){const b=button(label,()=>{},cls);b.addEventListener('pointerdown',e=>{e.preventDefault();if(!paused&&started&&!dead)fn();});b.addEventListener('click',e=>{if(e.detail===0&&!paused&&started&&!dead)fn();});return b;}
  function arrows(fn){const wrap=el('div','mini-arrows');DIRS.forEach((d,i)=>{const b=pad(d,()=>fn(i));b.innerHTML=arrowIcon(i);b.setAttribute('aria-label',['위','오른쪽','아래','왼쪽'][i]);wrap.append(b);});body.append(wrap);}
  function result(score,message,extras={}){rhythmMusic?.stop();tick=()=>{};input=()=>{};keyUp=()=>{};jobs=[];body.replaceChildren(el('div','mini-result-icon','✦'),el('h3','',message),el('p','',`연습 점수 ${Math.round(score)}점 · 오늘도 한 걸음 자랐어요!`),button('활동 완료하기',()=>finish(score,extras),'mini-primary'));}
  function begin(){if(beginning||started||dead)return;beginning=true;if(type==='direction'){started=true;body.replaceChildren();direction();return;}body.replaceChildren();const count=el('div','mini-countdown','3');body.append(count);sound(392);schedule(700,()=>{count.textContent='2';sound(440);});schedule(1400,()=>{count.textContent='1';sound(494);});schedule(2100,()=>{started=true;body.replaceChildren();const builtins={rhythm,direction,memory,makeup,compose};if(builtins[type])builtins[type]();else mountExtraMinigame(type,{body,el,button,schedule,sound,result,finish,rand,tier,o,now:()=>elapsed,setTick:fn=>tick=fn,setInput:fn=>input=fn,setKeyUp:fn=>keyUp=fn,setPause:fn=>onPause=fn,listen:(node,name,fn)=>node.addEventListener(name,e=>{if(!dead&&!paused&&started)fn(e);},{signal:events.signal})});});}
  body.append(el('div',`mini-intro-icon${type==='exercise'?' mini-exercise-icon':''}`,{rhythm:'♫',direction:'✧',memory:'↗',acting:'🎬',variety:'✿',makeup:'✦',compose:'♬',exercise:'🏃',beauty:'',meal:'🍱',rest:'☁',play:'🃏',gaming:'⭐',snack:'🍓',vacation:'🏖️'}[type]),el('p','mini-guide',GUIDES[type]),el('p','mini-muted',o.easy?'더 편하게 · 넉넉한 도움으로 함께해요':'틀려도 괜찮아요. 끝까지 하면 연습이 돼요!'),button('준비됐어요 · 시작',begin,'mini-primary'));
  if(type==='beauty')body.querySelector('.mini-intro-icon').innerHTML=BUBBLES_ICON;
  function rhythm(){
    const chart=vocalChart(tier),start=elapsed,total=RHYTHM_DURATION_MS,names=['도','레','미','파','솔'];
    rhythmMusic=o.startRhythm?.(chart.map(n=>n.at),{pitches:chart.map(n=>VOCAL_PITCHES[n.pitch])})||null;
    const songTime=()=>rhythmMusic?rhythmMusic.position():elapsed-start;
    let points=0,hits=0,pitch=2,lastPitchTime=0,lastTone=-1;const held=new Map();
    const meter=el('p','mini-meter'),lane=el('div','mini-lane'),panel=el('div','mini-pitch-panel'),pitchLabel=el('p','mini-pitch-label'),gauge=el('div','mini-pitch-gauge'),target=el('div','mini-pitch-target'),marker=el('div','mini-pitch-marker','내 음정');
    gauge.setAttribute('role','meter');gauge.setAttribute('aria-label','내 음정');gauge.setAttribute('aria-valuemin','0');gauge.setAttribute('aria-valuemax','4');
    gauge.append(target,marker);panel.append(pitchLabel,gauge);lane.append(el('span','mini-hitline','☆'));
    const notes=chart.map(n=>({...n,done:false,node:el('span','mini-note',names[n.pitch])}));notes.forEach(n=>lane.append(n.node));body.append(meter,panel,lane);
    const feedback=say();
    function updatePitch(t){const direction=Math.sign([...held.values()].reduce((a,b)=>a+b,0));pitch=movePitch(pitch,direction,t-lastPitchTime);lastPitchTime=t;const rounded=Math.round(pitch);if(direction&&rounded!==lastTone){sound(VOCAL_PITCHES[rounded],.18);lastTone=rounded;}}
    function paintPitch(){const next=notes.find(n=>!n.done);marker.style.left=(pitch/4*80+10)+'%';gauge.setAttribute('aria-valuenow',pitch.toFixed(2));gauge.setAttribute('aria-valuetext',names[Math.round(pitch)]);target.hidden=!next;if(next){target.style.left=(next.pitch/4*80+10)+'%';pitchLabel.textContent='다음 음정: '+names[next.pitch]+' · 내 음정: '+names[Math.round(pitch)];target.className='mini-pitch-target'+(Math.abs(pitch-next.pitch)<=.65?' matched':'');}}
    function judgmentSound(success){sound(success?784:196,success?.09:.18);if(success)schedule(90,()=>sound(1046.5,.12));}
    function hit(){const t=songTime();updatePitch(t);const n=notes.filter(n=>!n.done).sort((a,b)=>Math.abs(a.at-t)-Math.abs(b.at-t))[0];if(!n)return;const timing=rhythmScore(t-n.at,o.easy);if(!timing){judgmentSound(false);feedback.textContent='음표가 가운데 별에 올 때 박자를 눌러요!';return;}const score=vocalScore(timing,pitch,n.pitch);if(!score){judgmentSound(false);feedback.textContent='음정을 '+names[n.pitch]+'에 맞춰요! '+(pitch<n.pitch?'→ 높여요':'← 낮춰요');return;}n.done=true;n.node.hidden=true;n.node.remove();points+=score;hits++;judgmentSound(true);feedback.textContent='✓ 음정과 박자를 함께 맞췄어요!';paintPitch();}
    const controls=el('div','mini-pitch-controls');
    for(const [direction,label] of [[-1,'← 음정 낮추기'],[1,'→ 음정 높이기']]){
      const control=button(label,()=>{});control.setAttribute('aria-label',label+' · 누르고 있기');
      control.addEventListener('pointerdown',e=>{e.preventDefault();if(dead||paused||!started)return;updatePitch(songTime());control.setPointerCapture?.(e.pointerId);held.set('pointer'+e.pointerId,direction);},{signal:events.signal});
      const release=e=>{updatePitch(songTime());held.delete('pointer'+e.pointerId);};
      for(const event of ['pointerup','pointercancel','lostpointercapture'])control.addEventListener(event,release,{signal:events.signal});
      control.addEventListener('click',e=>{if(e.detail===0&&!dead&&!paused){pitch=Math.max(0,Math.min(4,pitch+direction*.5));sound(VOCAL_PITCHES[Math.round(pitch)],.18);paintPitch();}},{signal:events.signal});controls.append(control);
    }
    body.append(controls,pad('♫ 박자 맞추기 · Space',hit,'mini-tap'));
    input=e=>{updatePitch(songTime());if(e.code==='Space')hit();else if(e.key==='ArrowRight'||e.key==='ArrowLeft')held.set(e.key,e.key==='ArrowRight'?1:-1);};
    keyUp=e=>{updatePitch(songTime());held.delete(e.key);};onPause=()=>held.clear();
    tick=()=>{const t=songTime();updatePitch(t);lane.style.setProperty('--beat-glow',String(Math.max(0,1-(t%RHYTHM_BEAT_MS)/160)));meter.textContent=Math.max(0,Math.ceil((total-t)/1000))+'초 · 음정 + 박자 '+hits+'/'+notes.length+'개';notes.forEach(n=>{n.node.style.left=(50+(n.at-t)/(o.easy?4500:3200)*50)+'%';if(!n.done&&t-n.at>(o.easy?450:320)){n.done=true;n.node.hidden=true;judgmentSound(false);feedback.textContent='다음 음표의 음정을 준비해요!';}});paintPitch();if(t>=total){held.clear();result(points/notes.length,'노래 연습 완료!');}};paintPitch();
  }
  function direction(){
    let run,start=elapsed,hits=0;const meter=el('p','mini-meter'),arena=el('div','mini-dance-fall'),order=[3,2,0,1],cards=[];
    arena.setAttribute('aria-label','왼쪽 아래 위 오른쪽 네 레인 · 화살표가 초록 구간에 오면 누르세요');
    const zone=el('div','mini-dance-zone');arena.append(zone);
    order.forEach((d,i)=>{const receptor=el('span','mini-dance-receptor',DIRS[d]);receptor.innerHTML=arrowIcon(d);receptor.style.left=(12.5+i*25)+'%';arena.append(receptor);});body.append(meter,el('p','mini-guide','화살표가 초록 구간에 오면 같은 방향키! 10번 성공하면 완료해요.'),arena);const feedback=say();
    const songTime=()=>rhythmMusic?rhythmMusic.position():elapsed-start;
    function nextChart(){rhythmMusic?.stop();start=elapsed;run=createDanceRun(danceChart(tier,rand),o.easy);for(const card of cards)card.node.remove();cards.length=0;run.notes.forEach(n=>{const node=el('span','mini-dance-drop',DIRS[n.direction]);node.innerHTML=arrowIcon(n.direction);node.style.left=(12.5+order.indexOf(n.direction)*25)+'%';node.setAttribute('aria-label',['위','오른쪽','아래','왼쪽'][n.direction]);arena.append(node);cards.push({n,node});});rhythmMusic=o.startRhythm?.(run.notes.map(n=>n.at),{beatMs:DANCE_BEAT_MS,durationMs:DANCE_DURATION_MS,drums:true})||null;}
    function paint(t){run.advance(t);meter.textContent='성공 '+hits+'/10번';zone.style.height=(run.window/3000*156)+'%';cards.forEach(({n,node})=>{node.hidden=n.status!=='pending'||n.at-t>3300;node.style.top=(78-(n.at-t)/3000*78)+'%';node.className='mini-dance-drop'+(Math.abs(t-n.at)<=run.window?' ready':'');});}
    function answer(d){const t=songTime(),note=run.press(d,t);if(note){hits++;sound(700,.08);feedback.textContent='✓ 좋아요! '+hits+'/10번 성공';}else feedback.textContent='같은 화살표가 초록 구간에 왔을 때 눌러요!';paint(t);if(hits>=10)result(100,'댄스 연습 완료! 10번 성공했어요!');}
    const controls=el('div','mini-arrows');order.forEach(d=>{const control=pad(DIRS[d],()=>answer(d));control.innerHTML=arrowIcon(d);control.setAttribute('aria-label',['위','오른쪽','아래','왼쪽'][d]);controls.append(control);});body.append(controls);input=e=>{const d=KEYS.indexOf(e.key);if(d>=0)answer(d);};
    tick=()=>{let t=songTime();if(t>=DANCE_DURATION_MS){nextChart();t=0;}paint(t);};nextChart();paint(0);
  }
  function memory(){const sequences=memorySequences(rand),total=sequences.flat().length;let round=0,pos=0,points=0,roundPoints=0,showing=false,token=0;const meter=el('p','mini-meter'),cue=el('div','mini-direction'),trail=el('p','mini-memory-trail');body.append(meter,cue,trail);const feedback=say();function show(){if(showing)return;showing=true;pos=0;roundPoints=0;trail.textContent='';const id=++token,length=sequences[round].length;meter.textContent=`${round+1}/3번째 안무 · ${length}개 방향을 기억해요`;sequences[round].forEach((d,i)=>{schedule(i*950,()=>{if(token===id){cue.innerHTML=arrowIcon(d);cue.setAttribute('aria-label',['위','오른쪽','아래','왼쪽'][d]);sound(392+d*70);}});schedule(i*950+700,()=>{if(token===id)cue.textContent='·';});});schedule(length*950,()=>{if(token===id){showing=false;cue.textContent='내 차례!';meter.textContent=`${round+1}/3번째 안무 · 천천히 따라 해요`;}});}
    function answer(d){if(showing)return;const correct=d===sequences[round][pos];if(correct)roundPoints++;trail.textContent+=`${DIRS[d]}${correct?'✓':'♡'}  `;feedback.textContent=correct?'순서를 잘 기억했어요!':'괜찮아요. 남은 동작도 이어서 해요!';pos++;if(pos===sequences[round].length){points+=roundPoints;showing=true;const next=button(round===2?'연습 마치기':'다음 안무 보기',()=>{next.remove();if(round===2)result(points/total*100,'안무 기억 완료!');else{round++;showing=false;show();}},'mini-primary');body.append(next);}}
    arrows(answer);body.append(button('↻ 순서 다시 보기',()=>{if(!showing){feedback.textContent='순서를 다시 보고 처음 동작부터 해요.';show();}}));input=e=>{const d=KEYS.indexOf(e.key);if(d>=0)answer(d);};show();}
  function makeup(){const initial={eyeshadow:'none',eyeliner:'none',brow:'none',blush:'#efa5b5',lip:'#d98096',sparkle:false,...(o.appearance?.makeup||{})};let value={...initial};const history=[];const preview=el('div','mini-character');body.append(el('p','mini-guide','오늘 내 마음에 드는 색을 골라요. 외모 점수는 없어요.'),preview);function update(){if(o.renderCharacter)preview.innerHTML=o.renderCharacter({...o.appearance,makeup:value});else preview.textContent='✦ 나만의 반짝이는 모습 ✦';body.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(value[b.dataset.part]===b.dataset.color)));sparkle.setAttribute('aria-pressed',String(value.sparkle));}for(const [part,label]of [['blush','볼터치'],['lip','입술'],['eyeshadow','눈두덩 섀도'],['eyeliner','아이라인'],['brow','눈썹']]){const group=el('div','mini-palette');group.append(el('h3','',label));[['장미','#efa5b5'],['복숭아','#f4af8c'],['라벤더','#bd9adb'],['코랄','#d98096'],['브라운','#795548'],['차콜','#494252'],['없음','none']].forEach(([name,color])=>{const b=button(name,()=>{history.push({...value});value[part]=color;update();},'mini-swatch');b.dataset.color=color;b.dataset.part=part;b.style.setProperty('--swatch',color==='none'?'#fff':color);group.append(b);});body.append(group);}const sparkle=button('✦ 반짝이 켜기 / 끄기',()=>{history.push({...value});value.sparkle=!value.sparkle;update();});body.append(sparkle,button('↶ 한 번 되돌리기',()=>{if(history.length){value=history.pop();update();}}),button('처음 모습으로',()=>{history.push({...value});value={...initial};update();}),button('이 모습으로 완성!',()=>finish(80,{makeup:{...value}}),'mini-primary'));update();}
  function compose(){const notes=[{name:'도',f:261.63},{name:'레',f:293.66},{name:'미',f:329.63},{name:'솔',f:392},{name:'라',f:440}];let melody=[0,2,3,0],instrument='피아노',played=false,playing=false;const score=el('div','mini-score');body.append(el('p','mini-guide','각 마디의 음을 눌러 바꿔요. 어떤 멜로디든 좋아요!'),score);const cols=[];melody.forEach((_,i)=>{const col=el('div','mini-measure');col.append(el('strong','',`${i+1}마디`));notes.forEach((n,j)=>{const b=button(n.name,()=>{if(playing)return;melody[i]=j;played=false;done.disabled=true;paint();sound(n.f,.18);});b.dataset.note=j;col.append(b);});score.append(col);cols.push(col);});function paint(){cols.forEach((c,i)=>c.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.note)===melody[i]))));}const instruments=el('div','mini-instruments');['피아노','오르골','베이스'].forEach(name=>instruments.append(button(name,()=>{if(playing)return;instrument=name;played=false;done.disabled=true;paintInstruments();})));function paintInstruments(){instruments.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===instrument)));}const status=el('p','mini-feedback','완성 전에 한 번 끝까지 들어 보아요.');const play=button('▶ 내 노래 듣기',()=>{if(playing)return;playing=true;play.disabled=true;done.disabled=true;for(let i=0;i<4;i++)schedule(i*600,()=>{cols.forEach((c,j)=>c.classList.toggle('mini-playing',j===i));sound(notes[melody[i]].f*(instrument==='오르골'?2:instrument==='베이스'?.5:1),.35);status.textContent=`♫ ${i+1}마디 · ${notes[melody[i]].name}`;});schedule(2500,()=>{playing=false;played=true;play.disabled=false;done.disabled=false;cols.forEach(c=>c.classList.remove('mini-playing'));status.textContent='✦ 내 노래 완성! 다시 듣거나 음을 바꿀 수 있어요.';});},'mini-primary');const done=button('이 노래로 완성!',()=>{if(played&&!playing)finish(80,{melody:melody.map(n=>notes[n].name),instrument});},'mini-primary');done.disabled=true;body.append(instruments,status,play,done);input=e=>{if(/^[1-4]$/.test(e.key)&&!playing){const i=Number(e.key)-1;melody[i]=(melody[i]+1)%notes.length;played=false;done.disabled=true;paint();sound(notes[melody[i]].f,.18);}};paint();paintInstruments();}
  return {pause,resume,destroy};
}
