const DIRS = ['↑', '→', '↓', '←'];
const KEYS = ['ArrowUp', 'ArrowRight', 'ArrowDown', 'ArrowLeft'];
const TITLES = {rhythm:'반짝 보컬 스튜디오',direction:'한 걸음 댄스',memory:'안무 기억 놀이터',acting:'오늘의 영화 장면',variety:'이야기 꽃 피우기',makeup:'나만의 메이크업',compose:'네 마디 작은 노래'};
const GUIDES = {rhythm:'음표가 가운데 별에 오면 박자 버튼 또는 Space! 소리 없이도 할 수 있어요. 30초 동안 함께 노래해요.',direction:'큰 화살표와 같은 방향을 눌러요. 방향키도 좋아요! 화살표마다 2초 동안 기다려요.',memory:'화살표 순서를 보고 따라 눌러요. 세 번 연습해요. 헷갈리면 다시 볼 수 있고, 생각할 시간은 충분해요.',acting:'장면을 읽고 어울리는 마음과 대사를 골라요. 숫자 1~3으로도 고를 수 있어요. 천천히 읽어요!',variety:'주제에 어울리는 이야기 카드를 골라요. 힌트를 읽고 숫자 1~3 또는 카드를 눌러요.',makeup:'볼과 입술 색, 반짝이를 자유롭게 골라요. 어떤 조합도 멋진 내 표현! 외모는 채점하지 않아요.',compose:'네 마디에 음을 골라 나만의 노래를 만들어요. 악기를 고르고 한 번 끝까지 들으면 완성!'};
export const rhythmScore = (delta,easy=false) => Math.abs(delta) <= (easy?250:180) ? 100 : Math.abs(delta) <= (easy?450:320) ? 70 : 0;
export function startMinigame(container, options) {
  const o = {level:1,easy:false,seed:1,tone:()=>{},onComplete:()=>{},onCancel:()=>{},onFallback:()=>{},...options};
  const type = TITLES[o.type] ? o.type : 'rhythm';
  const tier = o.easy ? 0 : o.level >=16 ? 2 : o.level >=6 ? 1 : 0;
  let seed = (o.seed >>> 0)||1;
  const rand = () => {seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  let dead=false,paused=false,beginning=false,started=false,elapsed=0,last=0,raf=0,jobs=[],tick=()=>{},input=()=>{},finished=false;
  const events=new AbortController();
  const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  const root=el('section','minigame'); root.setAttribute('aria-label',TITLES[type]); container.replaceChildren(root);
  const header=el('header','mini-header'); const heading=el('h2','',TITLES[type]);header.append(heading);root.append(header);
  const button=(label,fn,cls='')=>{const b=el('button',`mini-button ${cls}`,label);b.type='button';b.addEventListener('click',()=>{if(!dead&&b.isConnected)fn();});return b;};
  const pauseButton=button('Ⅱ 잠깐 쉬기',()=>pause());header.append(pauseButton);
  const body=el('div','mini-body');root.append(body);
  const overlay=el('div','mini-overlay');overlay.hidden=true;root.append(overlay);
  const footer=el('footer','mini-footer');footer.append(button('일반 활동으로 마치기',()=>exit(o.onFallback)),button('취소 · 일정과 비용 돌려받기',()=>exit(o.onCancel)));root.append(footer);
  const say=()=>{const p=el('p','mini-feedback','함께 해 볼까요?');p.setAttribute('aria-live','polite');body.append(p);return p;};
  const schedule=(delay,fn)=>{jobs.push({at:elapsed+delay,fn});};
  const sound=(f,d=.12)=>{if(!paused&&!dead)o.tone(f,d);};
  function destroy(){if(dead)return;dead=true;cancelAnimationFrame(raf);jobs=[];events.abort();}
  function exit(fn){destroy();fn();}
  function finish(score,extras={}){if(finished||dead)return;finished=true;exit(()=>o.onComplete(Math.round(Math.max(0,Math.min(100,score))),extras));}
  function pause(){if(dead||paused)return;paused=true;overlay.replaceChildren(el('div','mini-pause-icon','☁'),el('h3','','잠깐 쉬어 가요'),el('p','','돌아오면 이어서 할 수 있어요.'),button('▶ 이어 하기',resume,'mini-primary'));overlay.hidden=false;body.inert=true;overlay.querySelector('button').focus();}
  function resume(){if(dead||!paused||document.hidden)return;paused=false;last=performance.now();overlay.hidden=true;body.inert=false;}
  document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();},{signal:events.signal});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();paused?resume():pause();return;}if(dead||paused||!started)return;if(e.target?.matches?.('input,textarea,select,[contenteditable=true]'))return;const gameKey=(KEYS.includes(e.key)&&['direction','memory'].includes(type))||(e.code==='Space'&&type==='rhythm')||(/^[1-4]$/.test(e.key)&&['acting','variety','compose'].includes(type));if(gameKey){e.preventDefault();if(!e.repeat)input(e);}}, {signal:events.signal});
  function frame(now){if(dead)return;if(!last)last=now;if(!paused){elapsed+=Math.min(now-last,100);const ready=jobs.filter(j=>j.at<=elapsed);jobs=jobs.filter(j=>j.at>elapsed);ready.forEach(j=>{if(!dead)j.fn();});if(!dead)tick(elapsed);}last=now;if(!dead)raf=requestAnimationFrame(frame);}
  raf=requestAnimationFrame(frame);
  function pad(label,fn,cls=''){const b=button(label,()=>{},cls);b.addEventListener('pointerdown',e=>{e.preventDefault();if(!paused&&started&&!dead)fn();});b.addEventListener('click',e=>{if(e.detail===0&&!paused&&started&&!dead)fn();});return b;}
  function arrows(fn){const wrap=el('div','mini-arrows');DIRS.forEach((d,i)=>{const b=pad(d,()=>fn(i));b.setAttribute('aria-label',['위','오른쪽','아래','왼쪽'][i]);wrap.append(b);});body.append(wrap);}
  function result(score,message,extras={}){tick=()=>{};input=()=>{};jobs=[];body.replaceChildren(el('div','mini-result-icon','✦'),el('h3','',message),el('p','',`연습 점수 ${Math.round(score)}점 · 오늘도 한 걸음 자랐어요!`),button('활동 완료하기',()=>finish(score,extras),'mini-primary'));}
  function begin(){if(beginning||started||dead)return;beginning=true;body.replaceChildren();const count=el('div','mini-countdown','3');body.append(count);sound(392);schedule(700,()=>{count.textContent='2';sound(440);});schedule(1400,()=>{count.textContent='1';sound(494);});schedule(2100,()=>{started=true;body.replaceChildren();({rhythm,direction,memory,acting:()=>cards(false),variety:()=>cards(true),makeup,compose})[type]();});}
  body.append(el('div','mini-intro-icon',{rhythm:'♫',direction:'✧',memory:'↗',acting:'🎬',variety:'✿',makeup:'✦',compose:'♬'}[type]),el('p','mini-guide',GUIDES[type]),el('p','mini-muted',o.easy?'더 편하게 · 넉넉한 도움으로 함께해요':'틀려도 괜찮아요. 끝까지 하면 연습이 돼요!'),button('준비됐어요 · 시작',begin,'mini-primary'));
  function rhythm(){const count=[8,12,16][tier],start=elapsed,total=30000;let points=0,hits=0;const notes=Array.from({length:count},(_,i)=>({at:2000+i*26000/(count-1),done:false,node:el('span','mini-note','♪')}));const meter=el('p','mini-meter');const lane=el('div','mini-lane');lane.setAttribute('aria-label','음표가 오른쪽에서 가운데 별로 다가와요');lane.append(el('span','mini-hitline','☆'));notes.forEach(n=>lane.append(n.node));body.append(meter,lane);const feedback=say();function hit(){const t=elapsed-start;const n=notes.filter(n=>!n.done).sort((a,b)=>Math.abs(a.at-t)-Math.abs(b.at-t))[0];if(!n)return;const score=rhythmScore(t-n.at,o.easy);if(!score){feedback.textContent='별에 조금 더 가까워지면 눌러요!';return;}n.done=true;n.node.hidden=true;points+=score;hits++;feedback.textContent=score===100?'✦ 정확해요!':'♡ 거의 맞았어요!';sound(score===100?659:523);}
    body.append(pad('♫ 박자 맞추기 · Space',hit,'mini-tap'));input=e=>{if(e.code==='Space')hit();};tick=()=>{const t=elapsed-start;meter.textContent=`${Math.max(0,Math.ceil((total-t)/1000))}초 · ${hits}/${count}개`;notes.forEach(n=>{n.node.style.left=`${50+(n.at-t)/(o.easy?4500:3200)*50}%`;if(!n.done&&t-n.at>(o.easy?450:320)){n.done=true;n.node.hidden=true;feedback.textContent='다음 음표에서 다시 만나자!';}});if(t>=total)result(points/count,'노래 연습 완료!');};}
  function direction(){const count=[6,9,12][tier],pattern=Array.from({length:count},()=>Math.floor(rand()*4));const start=elapsed,spacing=25000/count;let index=0,answered=false,points=0;const meter=el('p','mini-meter'),cue=el('div','mini-direction','준비'),bar=el('progress','mini-progress');bar.max=2000;body.append(meter,cue,bar);const feedback=say();function answer(d){const t=elapsed-start-index*spacing;if(index>=count||answered||t<0||t>2000)return;answered=true;const good=d===pattern[index];if(good){points++;sound(587);}feedback.textContent=good?'✦ 딱 맞는 한 걸음!':'괜찮아요! 다음 화살표를 보아요.';cue.textContent=good?'✓':'♡';}arrows(answer);input=e=>{const d=KEYS.indexOf(e.key);if(d>=0)answer(d);};tick=()=>{const t=elapsed-start;const next=Math.floor(t/spacing);if(next!==index){index=next;answered=false;}if(t>=25000){result(points/count*100,'댄스 연습 완료!');return;}const remaining=2000-(t-index*spacing);meter.textContent=`${Math.ceil((25000-t)/1000)}초 · ${index+1}/${count}번째`;bar.value=Math.max(0,remaining);if(!answered){cue.textContent=remaining>0?DIRS[pattern[index]]:'다음 준비';if(remaining<=0){answered=true;feedback.textContent='놓쳐도 괜찮아요. 다음 동작으로!';}}};}
  function memory(){const length=[2,3,4][tier];const sequences=Array.from({length:3},()=>Array.from({length},()=>Math.floor(rand()*4)));let round=0,pos=0,points=0,roundPoints=0,showing=false,token=0;const meter=el('p','mini-meter'),cue=el('div','mini-direction'),trail=el('p','mini-memory-trail');body.append(meter,cue,trail);const feedback=say();function show(){if(showing)return;showing=true;pos=0;roundPoints=0;trail.textContent='';const id=++token;meter.textContent=`${round+1}/3번째 안무 · 순서를 보아요`;sequences[round].forEach((d,i)=>{schedule(i*950,()=>{if(token===id){cue.textContent=DIRS[d];sound(392+d*70);}});schedule(i*950+700,()=>{if(token===id)cue.textContent='·';});});schedule(length*950,()=>{if(token===id){showing=false;cue.textContent='내 차례!';meter.textContent=`${round+1}/3번째 안무 · 천천히 따라 해요`;}});}
    function answer(d){if(showing)return;const correct=d===sequences[round][pos];if(correct)roundPoints++;trail.textContent+=`${DIRS[d]}${correct?'✓':'♡'}  `;feedback.textContent=correct?'순서를 잘 기억했어요!':'괜찮아요. 남은 동작도 이어서 해요!';pos++;if(pos===length){points+=roundPoints;showing=true;const next=button(round===2?'연습 마치기':'다음 안무 보기',()=>{next.remove();if(round===2)result(points/(3*length)*100,'안무 기억 완료!');else{round++;showing=false;show();}},'mini-primary');body.append(next);}}
    arrows(answer);body.append(button('↻ 순서 다시 보기',()=>{if(!showing){feedback.textContent='순서를 다시 보고 처음 동작부터 해요.';show();}}));input=e=>{const d=KEYS.indexOf(e.key);if(d>=0)answer(d);};show();}
  function cards(variety){const scenes=variety?[
    ['비 오는 날의 즐거운 일','힌트: 비 오는 날 할 수 있는 즐거운 일을 찾아요.',['창가에서 빗소리를 들어요','사막에서 모래성을 쌓아요','스키장에서 눈사람을 만들어요'],0,'빗소리 이야기가 오늘의 주제와 잘 이어져요!'],
    ['친구가 첫 무대에 서요','힌트: 친구에게 힘이 되는 말을 골라요.',['내일 간식은 뭘까요?','네 연습을 봤어. 응원할게!','제 신발이 반짝여요'],1,'따뜻한 응원이 친구에게 용기를 줘요!'],
    ['우리 그룹을 소개해요','힌트: 함께하는 즐거움을 들려줘요.',['어제 구름은 하얬어요','의자는 네 다리예요','다섯 목소리로 행복을 전해요'],2,'그룹의 매력이 이야기에 담겼어요!']
  ]:[
    ['잃어버린 강아지를 다시 만났어요','어떤 마음과 대사가 어울릴까요?',['안도하며: 정말 보고 싶었어!','졸린 목소리로: 잘 자','의아하게: 이건 무슨 책이지?'],0,'다시 만난 기쁨과 안도가 잘 전해졌어요.'],
    ['친구가 무대에 오르기 전 떨고 있어요','친구에게 용기를 주는 장면이에요.',['짜증내며: 빨리 가자','다정하게: 내가 곁에 있을게','놀라며: 비행기다!'],1,'다정한 표정이 친구에게 힘을 주었어요.'],
    ['오랫동안 준비한 꿈의 무대가 열렸어요','주인공의 벅찬 마음을 표현해요.',['무심하게: 오늘은 월요일','졸리게: 더 자고 싶어','기쁘게: 드디어 우리 차례야!'],2,'기쁨이 관객에게도 전해졌어요!']
  ];let index=0,points=0,locked=false;function draw(){body.replaceChildren();locked=false;const s=scenes[index];body.append(el('p','mini-meter',`${index+1}/3 장면 · 읽기 시간은 넉넉해요`),el('div','mini-scene-icon',variety?'🎙':'🎬'),el('h3','mini-scene-title',s[0]),el('p','mini-guide',s[1]));const deck=el('div','mini-card-deck');s[2].forEach((text,i)=>deck.append(button(`${i+1}. ${text}`,()=>choose(i),'mini-choice')));body.append(deck);input=e=>{if(/^[1-3]$/.test(e.key))choose(Number(e.key)-1);};}function choose(i){if(locked)return;locked=true;const s=scenes[index],good=i===s[3];points+=good?100:60;body.querySelectorAll('.mini-choice').forEach(b=>b.disabled=true);body.append(el('p','mini-feedback',good?`✦ ${s[4]}`:`♡ 새로운 해석이에요! ${s[4]}`),button(index===2?'연습 마치기':'다음 장면',()=>{index++;index===3?result(points/3,variety?'이야기 연습 완료!':'장면 연기 완료!'):draw();},'mini-primary'));sound(good?659:440);}draw();}
  function makeup(){const initial={blush:'#efa5b5',lip:'#d98096',sparkle:false,...(o.appearance?.makeup||{})};let value={...initial};const history=[];const preview=el('div','mini-character');body.append(el('p','mini-guide','오늘 내 마음에 드는 색을 골라요. 외모 점수는 없어요.'),preview);function update(){if(o.renderCharacter)preview.innerHTML=o.renderCharacter({...o.appearance,makeup:value});else preview.textContent='✦ 나만의 반짝이는 모습 ✦';body.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(value[b.dataset.part]===b.dataset.color)));sparkle.setAttribute('aria-pressed',String(value.sparkle));}for(const [part,label]of [['blush','볼터치'],['lip','입술']]){const group=el('div','mini-palette');group.append(el('h3','',label));[['장미','#efa5b5'],['복숭아','#f4af8c'],['라벤더','#bd9adb'],['코랄','#d98096'],['없음','none']].forEach(([name,color])=>{const b=button(name,()=>{history.push({...value});value[part]=color;update();},'mini-swatch');b.dataset.color=color;b.dataset.part=part;b.style.setProperty('--swatch',color==='none'?'#fff':color);group.append(b);});body.append(group);}const sparkle=button('✦ 반짝이 켜기 / 끄기',()=>{history.push({...value});value.sparkle=!value.sparkle;update();});body.append(sparkle,button('↶ 한 번 되돌리기',()=>{if(history.length){value=history.pop();update();}}),button('처음 모습으로',()=>{history.push({...value});value={...initial};update();}),button('이 모습으로 완성!',()=>finish(80,{makeup:{...value}}),'mini-primary'));update();}
  function compose(){const notes=[{name:'도',f:261.63},{name:'레',f:293.66},{name:'미',f:329.63},{name:'솔',f:392},{name:'라',f:440}];let melody=[0,2,3,0],instrument='피아노',played=false,playing=false;const score=el('div','mini-score');body.append(el('p','mini-guide','각 마디의 음을 눌러 바꿔요. 어떤 멜로디든 좋아요!'),score);const cols=[];melody.forEach((_,i)=>{const col=el('div','mini-measure');col.append(el('strong','',`${i+1}마디`));notes.forEach((n,j)=>{const b=button(n.name,()=>{if(playing)return;melody[i]=j;played=false;done.disabled=true;paint();sound(n.f,.18);});b.dataset.note=j;col.append(b);});score.append(col);cols.push(col);});function paint(){cols.forEach((c,i)=>c.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.note)===melody[i]))));}const instruments=el('div','mini-instruments');['피아노','오르골','베이스'].forEach(name=>instruments.append(button(name,()=>{if(playing)return;instrument=name;played=false;done.disabled=true;paintInstruments();})));function paintInstruments(){instruments.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===instrument)));}const status=el('p','mini-feedback','완성 전에 한 번 끝까지 들어 보아요.');const play=button('▶ 내 노래 듣기',()=>{if(playing)return;playing=true;play.disabled=true;done.disabled=true;for(let i=0;i<4;i++)schedule(i*600,()=>{cols.forEach((c,j)=>c.classList.toggle('mini-playing',j===i));sound(notes[melody[i]].f*(instrument==='오르골'?2:instrument==='베이스'?.5:1),.35);status.textContent=`♫ ${i+1}마디 · ${notes[melody[i]].name}`;});schedule(2500,()=>{playing=false;played=true;play.disabled=false;done.disabled=false;cols.forEach(c=>c.classList.remove('mini-playing'));status.textContent='✦ 내 노래 완성! 다시 듣거나 음을 바꿀 수 있어요.';});},'mini-primary');const done=button('이 노래로 완성!',()=>{if(played&&!playing)finish(80,{melody:melody.map(n=>notes[n].name),instrument});},'mini-primary');done.disabled=true;body.append(instruments,status,play,done);input=e=>{if(/^[1-4]$/.test(e.key)&&!playing){const i=Number(e.key)-1;melody[i]=(melody[i]+1)%notes.length;played=false;done.disabled=true;paint();sound(notes[melody[i]].f,.18);}};paint();paintInstruments();}
  return {pause,resume,destroy};
}
