import {readFile, writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';

// Like splash-club, ship a classic script for file:// launches. Each source
// module keeps its own scope so private names never collide when bundled.
const sources = ['data.js', 'core.js', 'character.js', 'audio.js', 'minigames.js', 'storage.js', 'main.js'];
export async function buildBundle() {
  const parts = [], available = new Set();
  for (const file of sources) {
    let source = (await readFile(new URL(`src/${file}`, import.meta.url), 'utf8')).replace(/\r\n/g, '\n');
    source = source.replace(/^import\s+(\{[^}]+\}|\*\s+as\s+\w+)\s+from\s+['"]\.\/([\w-]+\.js)['"];\s*$/gm, (_, binding, dependency) => {
      if (!available.has(dependency)) throw new Error(`Dependency ${dependency} must precede ${file}.`);
      const local = binding.startsWith('*') ? binding.replace(/^\*\s+as\s+/, '') : binding.replace(/\b(\w+)\s+as\s+(\w+)\b/g, '$1: $2');
      return `const ${local} = modules[${JSON.stringify(dependency)}];\n`;
    });
    const exports = [...source.matchAll(/^export\s+(?:const|function)\s+(\w+)/gm)].map(match => match[1]);
    source = source.replace(/^export (?=(?:const|function)\b)/gm, '');
    if (/^\s*(?:import|export)\s/m.test(source) || /\bimport\s*\(|\bimport\.meta\b/.test(source)) {
      throw new Error(`Unsupported module syntax in ${file}; update the bundler first.`);
    }
    parts.push(`// ---- src/${file} ----\nmodules[${JSON.stringify(file)}] = (() => {\n${source.trim()}\nreturn Object.freeze({${exports.join(', ')}});\n})();`);
    available.add(file);
  }
  return `// Generated by node build.mjs. Edit src/*.js, then run npm run build.\n(function () {\n'use strict';\nconst modules = Object.create(null);\n${parts.join('\n\n')}\n})();\n`;
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  await writeFile(new URL('game.bundle.js', import.meta.url), await buildBundle());
  console.log('Built game.bundle.js (file:// and HTTP compatible)');
}
