import {readFile, writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';

// These three local modules have no external dependencies. Keep the source modules
// for development/tests and ship a classic script for direct file:// launches.
const sources = ['core.js', 'character.js', 'app.js'];
export async function buildBundle() {
  const parts = [];
  for (const file of sources) {
    let source = (await readFile(new URL(file, import.meta.url), 'utf8')).replace(/\r\n/g, '\n');
    source = source.replace(/^import\s+\{[^}]*\}\s+from\s+['"]\.\/(core|character)\.js['"];\s*$/gm, '');
    source = source.replace(/^export (?=(?:const|function)\b)/gm, '');
    if (/^\s*(?:import|export)\s/m.test(source)) {
      throw new Error(`Unsupported module syntax in ${file}; update the bundler first.`);
    }
    parts.push(`// ---- ${file} ----\n${source.trim()}`);
  }
  return `// Generated by node build.mjs. Edit core.js, character.js and app.js instead.\n(function () {\n'use strict';\n${parts.join('\n\n')}\n})();\n`;
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  await writeFile(new URL('game.bundle.js', import.meta.url), await buildBundle());
  console.log('Built game.bundle.js (file:// and HTTP compatible)');
}
