export const KEY='splash-club-save-v1';
export const COLORS=['#38b7a3','#f17d79','#a28bd4','#e8bd46','#599bd5'];
const LEGACY_ITEMS=[{id:'cap',name:'구름 수영모',type:'수영모',price:80,stat:'stability',bonus:.04,desc:'안정성 +4',icon:'◡'},{id:'suit',name:'웨이브 수영복',type:'수영복',price:140,stat:'base',bonus:.04,desc:'기본 속도 +0.04',icon:'♧'},{id:'fins',name:'오리발 물갈퀴',type:'물갈퀴',price:180,stat:'power',bonus:.12,desc:'추진력 +12',icon:'♬'},{id:'goggles',name:'클리어 수영안경',type:'수영안경',price:100,stat:'stability',bonus:.06,desc:'안정성 +6',icon:'∞'}];
export const SLOT_COUNT=10;
export const DISTANCES={practice:50,race:100};
export const TIMING={perfect:.14,good:.24,hit:.32};
const THEMES=['구름','딸기','복숭아','레몬','민트','라벤더','하늘','무지개','별빛','달빛','오리','토끼','고양이','곰돌이','수달','돌고래','조개','산호','진주','물방울','벚꽃','해바라기','솜사탕','오로라','은하수'];
export const ITEMS=LEGACY_ITEMS.flatMap(item=>THEMES.map((theme,index)=>({...item,id:index?`${item.id}-${index}`:item.id,slot:item.id,tier:Math.floor(index/5)+1,hue:index*29,name:index?`${theme} ${item.type}`:item.name,price:item.price+index*20,bonus:Number((item.bonus+Math.floor(index/5)*(item.stat==='base'?.008:.015)).toFixed(3)),desc:`${{base:'속도',power:'추진력',stability:'안정성'}[item.stat]} +${(item.bonus+Math.floor(index/5)*(item.stat==='base'?.008:.015)).toFixed(3)}${item.stat==='base'?' m/s':''}`})));
export const ACTIVITIES=[
  {id:'eat',name:'먹기',icon:'🍙',energy:15,stat:'power',bonus:.04,label:'추진력 +0.04'},
  {id:'sleep',name:'자기',icon:'🛏️',energy:0,stat:'base',bonus:.025,label:'속도 +0.025 m/s · 다음 날'},
  {id:'tv',name:'TV 보기',icon:'📺',energy:10,stat:'stability',bonus:.04,label:'안정성 +0.04'},
  {id:'tablet',name:'태블릿 보기',icon:'📱',energy:12,stat:'power',bonus:.035,label:'추진력 +0.035'},
  {id:'bath',name:'목욕하기',icon:'🛁',energy:15,stat:'base',bonus:.02,label:'속도 +0.020 m/s'},
  {id:'play',name:'인형과 놀기',icon:'🧸',energy:12,stat:'power',bonus:.03,label:'추진력 +0.03'},
  {id:'toys',name:'장난감으로 놀기',icon:'🧩',energy:12,stat:'stability',bonus:.03,label:'안정성 +0.03'},
  {id:'rest',name:'쉬기',icon:'🛋️',energy:8,stat:'stability',bonus:.035,label:'안정성 +0.035'}
];
export function slotKey(slot=0){if(!Number.isInteger(slot)||slot<0||slot>=SLOT_COUNT)throw Error('Invalid slot');return `splash-club-save-v2-slot-${slot+1}`;}
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const needXP=l=>80+(l-1)*40;
export const START_STATS=[{base:.68,power:.65,stability:.5},{base:.66,power:.8,stability:.4},{base:.68,power:.55,stability:.6},{base:.72,power:.55,stability:.45},{base:.65,power:.75,stability:.58}];
export function newPlayer(name,color){return {version:2,day:1,lastPracticeDay:0,energy:60,buffs:[],name:name.trim().slice(0,12)||'모찌',color:clamp(color,0,4),level:1,xp:0,coins:120,stats:{...START_STATS[clamp(color,0,4)]},owned:[],equipped:[],records:{races:0,practices:0,best:null,maxCombo:0},place:'village',settings:{sound:true,offset:0},savedAt:null};}
function validBase(p){const n=(v,a,b)=>Number.isFinite(v)&&v>=a&&v<=b;return !!p&&[1,2].includes(p.version)&&typeof p.name==='string'&&p.name.length>0&&p.name.length<=12&&Number.isInteger(p.color)&&n(p.color,0,4)&&Number.isInteger(p.level)&&n(p.level,1,20)&&n(p.xp,0,needXP(p.level)-1)&&Number.isInteger(p.coins)&&n(p.coins,0,1e9)&&p.stats&&n(p.stats.base,.1,3)&&n(p.stats.power,0,3)&&n(p.stats.stability,0,1)&&Array.isArray(p.owned)&&Array.isArray(p.equipped)&&new Set(p.owned).size===p.owned.length&&new Set(p.equipped).size===p.equipped.length&&p.owned.every(id=>ITEMS.some(i=>i.id===id))&&p.equipped.every(id=>p.owned.includes(id))&&p.records&&['races','practices','maxCombo'].every(k=>Number.isInteger(p.records[k])&&n(p.records[k],0,1e9))&&(p.records.best===null||n(p.records.best,0,10000))&&['village','home','shop','practice','stadium','beach'].includes(p.place)&&p.settings&&typeof p.settings.sound==='boolean'&&n(p.settings.offset,-150,150)&&(p.savedAt===null||typeof p.savedAt==='string'&&Number.isFinite(Date.parse(p.savedAt)));}
export function validSave(p){return validBase(p)&&(p.version===1||p.lastPracticeDay===undefined||(Number.isSafeInteger(p.lastPracticeDay)&&p.lastPracticeDay>=0&&p.lastPracticeDay<=p.day))&&(p.version===1||(Number.isSafeInteger(p.day)&&p.day>=1&&Number.isInteger(p.energy)&&p.energy>=0&&p.energy<=100&&Array.isArray(p.buffs)&&p.buffs.length<=ACTIVITIES.length&&new Set(p.buffs.map(b=>b?.id)).size===p.buffs.length&&p.buffs.every(b=>b&&ACTIVITIES.some(a=>a.id===b.id)&&Number.isInteger(b.remaining)&&b.remaining>=1&&b.remaining<=3)&&new Set(p.equipped.map(id=>ITEMS.find(i=>i.id===id).slot)).size===p.equipped.length));}
export function readSave(storage,slot=0){try{const key=slotKey(slot);let raw=storage.getItem(key);if(raw===null||raw===undefined){if(slot===0)raw=storage.getItem(KEY);}if(!raw)return {player:null,error:null};let p=JSON.parse(raw);if(!validSave(p))throw Error('invalid');if(p.version===1)p={...p,version:2,day:1,energy:60,buffs:[],records:{...p.records,best:null}};p.lastPracticeDay??=0;return {player:p,error:null};}catch{return {player:null,error:'저장 데이터를 읽을 수 없어요. 다른 슬롯을 선택하거나 새로 시작해 주세요.'};}}
export function readSlots(storage){return Array.from({length:SLOT_COUNT},(_,slot)=>readSave(storage,slot));}
export function savePlayer(storage,p,slot=0){const next={...p,savedAt:new Date().toISOString()};try{if(!validSave(next)||next.version!==2)return false;storage.setItem(slotKey(slot),JSON.stringify(next));p.savedAt=next.savedAt;return true;}catch{return false;}}
export function stats(p){const s={...p.stats};for(const id of p.equipped){const i=ITEMS.find(x=>x.id===id);s[i.stat]+=i.bonus;}for(const buff of p.buffs||[]){const activity=ACTIVITIES.find(a=>a.id===buff.id);s[activity.stat]+=activity.bonus;}return s;}
export function purchase(p,id){const i=ITEMS.find(x=>x.id===id);if(!i||p.owned.includes(id)||p.coins<i.price)return false;p.coins-=i.price;return acquireItem(p,id);}
export function acquireItem(p,id){if(!ITEMS.some(i=>i.id===id)||p.owned.includes(id))return false;p.owned.push(id);equip(p,id);return true;}
export function equip(p,id){const item=ITEMS.find(i=>i.id===id);if(!item||!p.owned.includes(id))return false;if(p.equipped.includes(id))p.equipped=p.equipped.filter(x=>x!==id);else p.equipped=[...p.equipped.filter(x=>ITEMS.find(i=>i.id===x).slot!==item.slot),id];return true;}
export function doActivity(p,id){const a=ACTIVITIES.find(a=>a.id===id);if(!a||p.energy<a.energy||a.id==='sleep'&&p.day>=Number.MAX_SAFE_INTEGER)return false;p.energy-=a.energy;if(a.id==='sleep'){if(p.lastPracticeDay!==p.day)for(const key of ['base','power','stability'])p.stats[key]=Math.max(START_STATS[p.color][key]*.8,p.stats[key]*.99);p.day++;}p.buffs=p.buffs.filter(b=>b.id!==id);p.buffs.push({id,remaining:3});return true;}
// Snapshot bonuses for the whole swim; abandoning also consumes one charge.
export function beginSwim(p){const snapshot=stats(p);p.buffs=p.buffs.map(b=>({...b,remaining:b.remaining-1})).filter(b=>b.remaining>0);return snapshot;}
export function findNote(groups,key,time){let best=null;for(const group of groups){if(group.time>time+TIMING.hit)break;const index=group.keys.indexOf(key),delta=Math.abs(group.time-time);if(index>=0&&group.scores[index]===null&&delta<=TIMING.hit+1e-6&&(!best||delta<best.delta))best={group,index,delta};}return best;}
export const comboBonus=c=>Math.min(c*.005,.2);
export const targetSpeed=(s,g,c)=>s.base*(1+s.power*g)*(1+comboBonus(c));
export function judge(error){const a=Math.abs(error);return a<=TIMING.perfect+1e-6?1:a<=TIMING.good+1e-6?.7:a<=TIMING.hit+1e-6?.3:0;}
export function applyGroup(actor,scores,s){const avg=scores.reduce((a,b)=>a+b,0)/scores.length;const rate=avg>=actor.gauge?.25:clamp(.30-(s.stability-.4)*.6,.18,.30);actor.gauge=clamp(actor.gauge+rate*(avg-actor.gauge),0,1);actor.combo=scores.every(x=>x>=.7)?actor.combo+1:0;actor.maxCombo=Math.max(actor.maxCombo,actor.combo);}
export function reward(p,mode,rank,accuracy,maxCombo,time){if(mode==='practice')p.lastPracticeDay=p.day;const xp=mode==='practice'?25+Math.round(accuracy*.35):45+(5-rank)*12+Math.round(accuracy*.25);const coins=mode==='practice'?15+Math.round(accuracy*.15):25+(5-rank)*15;const energy=Math.min(100-p.energy,mode==='practice'?30:50);p.energy+=energy;const old=p.level;p.xp+=xp;p.coins+=coins;while(p.level<20&&p.xp>=needXP(p.level)){p.xp-=needXP(p.level);p.level++;p.stats.base+=.012;p.stats.power+=.012;p.stats.stability+=.008;}if(p.level===20)p.xp=0;p.records[mode==='practice'?'practices':'races']++;p.records.maxCombo=Math.max(p.records.maxCombo,maxCombo);if(mode==='race')p.records.best=p.records.best===null?time:Math.min(time,p.records.best);return {xp,coins,energy,levels:p.level-old};}
export function difficulty(level){return {label:level<3?'입문 리그':level<6?'도전 리그':'챔피언 리그',bpm:level<3?80:level<6?88:96,perfect:Math.min(.67,.27+level*.025),good:.23};}
export function chart(mode,level,duration=180){const bpm=mode==='practice'?80:difficulty(level).bpm;const step=60/bpm;const groups=[];for(let i=0,t=2.4;t<duration;i++,t+=step){let keys=[[0],[2],[1],[3]][i%4];if(mode==='race'&&level>=10&&i%16>=12)keys=i%2===0?[0,3]:[2,1];groups.push({time:t,keys,scores:keys.map(()=>null),done:false});}return groups;}
export function random(seed){return ()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
